### ISSUE TITLE
.bib file interface

### ISSUE THREAD

**Issue by matteo339** [TeXworks/texworks#1018]
It would be very convenient to be able to select a `.bib` file and have an interface listing all bibliographic records.
In this way, upon selecting the record, the related citationkey would be inserted into the `.tex` source.

Matteo

**Comment by stloeffler** [comment]
This exists (sort of). If you add a `%!TeX bibfile=yourfile.bib` line to the beginning of your file, you can use "Edit > Insert Citations..." to display a dialog with the bibliography items, where you can filter entries and select those you want to cite. There currently is no dialog to insert the `%!TeX bibfile...` line, and there is no support yet for specifying bib-files anywhere else than in the current file (e.g., it's not possible to specify them in the root file, or on a per-project basis), but this is planned for the future.

**Comment by matteo339** [comment]
> If you add a `%!TeX bibfile=yourfile.bib` line to the beginning of your file, you can use "Edit > Insert Citations..." to display a dialog with the bibliography items, where you can filter entries and select those you want to cite. 

Great... I didn't know about this feature.
At this point I suggest two implementations:
1) the addition of the 'citationkey' column, which is useful when using non-standard entrytypes (see below). Also, since it may be unnecessary for some, a check box could be added in the Preferences to enable/disable the display of this column.
<img width="661" alt="Screenshot 2023-10-25 at 11 12 08" src="https://github.com/TeXworks/texworks/assets/111273603/5ae0e274-467d-4328-abc3-0e0728197154">

2) Currently this function adds the command `\cite{}`, but the user may need to use other commands, which depend on the style of the citations (`\parencite`, `\footcite`, `\autocite`, ...). It would be useful, in the Preferences, to be able to set the appropriate command, as in JabRef (see below).
<img width="449" alt="Screenshot 2023-10-25 at 11 39 38" src="https://github.com/TeXworks/texworks/assets/111273603/14080e47-8198-40ad-923f-ad275822fe07">

Matteo
