### ISSUE TITLE
Version not provided for winget

### ISSUE THREAD

**Issue by chiefrocker86** [TeXworks/texworks#1020]
**Bug description:**
It seems Texworks does not provide a version for winget so commands like ` winget upgrade texworks` are not working correctly.

**Steps to reproduce the problem:**

1. Open cmd
2. run ` winget upgrade texworks` 

**Expected behavior:**
Update to the latest version or do nothing.

**General information:**
_TeXworks version_: 0.6.7
_TeXworks obtained from_: via winget
_Operating system_: Windows 10 (64-Bit)

**Additional information:**
Provisioning the version as wingets needs it should fix the issue.

**Comment by kman3107** [comment]
Still an issue with 0.6.9

**Comment by stloeffler** [comment]
[0.6.8 and 0.6.9](https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/TUG/TeXworks) should be available in winget by now
