### ISSUE TITLE
'Insert Citations' feature: implementations request

### ISSUE THREAD

**Issue by matteofg** [TeXworks/texworks#1034]
This issue is a continuation of #1018.

I didn't know about this feature. I suggest two implementations:

1. the addition of the 'citationkey' column, which is useful when using non-standard entrytypes (see below). Also, since it may be unnecessary for some, a check box could be added in the Preferences to enable/disable the display of this column.
<img width="661" alt="277938406-5ae0e274-467d-4328-abc3-0e0728197154" src="https://github.com/TeXworks/texworks/assets/111273603/053c0396-26a5-415c-be63-20d9b465ca7b">

2. Currently this function adds the command `\cite{}`, but the user may need to use other commands, which depend on the style of the citations (`\parencite`, `\footcite`, `\autocite`, ...). It would be useful, in the Preferences, to be able to set the appropriate command, as in JabRef (see below).
<img width="449" alt="277946683-14080e47-8198-40ad-923f-ad275822fe07-2" src="https://github.com/TeXworks/texworks/assets/111273603/cecffe63-03e3-4b71-8fec-12682a2ec7bc">

**Comment by matteofg** [comment]
Sorry, but I can't figure out how to customize the “Insert Citations…” dialog.
Where should I look for `citationDialogBibTeXFields`?
<img width="912" alt="Image" src="https://github.com/user-attachments/assets/d738ae64-415c-4b42-b021-79bad7a42d33" />

**Comment by stloeffler** [comment]
I think you are in the right place. Note that the `citationDialogBibTeXFields` entry does not normally exist (in which case the default settings are used). In that case you can simply add it. I think you should be able to add a new entry by hovering over an existing one and clicking the `+` icon, but unfortunately I am not too familiar with macOS. However, if it doesn't work that way, you can simply open the `org.tug.TeXworks.plist` file in any text editor and add the line there.

**Comment by matteofg** [comment]
> Note that the `citationDialogBibTeXFields` entry does not normally exist

Just as I thought...

I correctly set `citationDialogBibTeXFields` and `citeCommand`, but it wasn’t easy. It took me many attempts to get there because I didn’t know how to set the keys (array? string?) and the values (with or without quotes?). I'm not a computer scientist, and the "Short manual for TeXworks" doesn't say anything about it.
Therefore, I suggest making these keys available in the .plist file from the start so that users can easily modify the default values.
