### ISSUE TITLE
tikz not included in 2023 package for Linuxmint

### ISSUE THREAD

**Issue by campagnol33** [TeXworks/texworks#1062]
I just installed TeXworks on Linux, because I have for long used TeXshop on MacOS and the environments are apparently similar. Yet tikz.sty is not found during typsetting. 
In fact, I do not find it in /usr/share/texlive where TeXworks has been apparently automatically installed by the Linuxmint Software manager.

Should I try to remove the installation and install texlive? This seems cumbersome, and I would prefer an autoinstaller package: is there an ISO file for a full install of texlive, usable by TeXworks? Or is there a simple way to add tikz? Thanks for your help!

**General information:**
_TeXworks version_:  0.6.8
_TeXworks obtained from_: v6.4.2 by The Qt Company.
_Operating system_: Linuxmint Mate 22

**Comment by jlaurens** [comment]
Are you able to typeset your document from the command line?

**Comment by campagnol33** [comment]
Hi Jlaurens. When typesetting (either in the TeXworks interface or by a pdflatex command in a terminal), I get the error message "File tikz.sty not found". Actually, I did not find tikz.* in the distribution, and would be unable to fix a path.

**Comment by stloeffler** [comment]
It [seems](https://community.linuxmint.com/software/view/texlive-pictures) the package containing tikz is called `texlive-pictures`.
Alternatively, a full TeXLive image (independent of the system's package manager) can be found at https://www.tug.org/texlive/. TeXworks should work with both.
