### ISSUE TITLE
Meta Information not shown

### ISSUE THREAD

**Issue by hpvd** [TeXworks/texworks#1063]
**Bug description:**
includes meta informations not shown in meta window

**Steps to reproduce the problem:**

```
\DocumentMetadata{
  lang        = de,
  pdfversion  = 2.0,
  pdfstandard = ua-2,
  pdfstandard = a-4f, %or a-4
  testphase   = 
   {phase-III,
    title,
    table,
    math,
    firstaid}  
}

\documentclass{article}

\title{test title}
\author{test author}

\begin{document}
\section{test section}
test text in section


\end{document}

```
**Expected behavior:**
show available information as acrobat does

**General information:**
_TeXworks version_: 0.69 Miktex 24.4
_TeXworks obtained from_:  miktex
_Operating system_: W11

**Additional information:**

![2024-10-03_12h15_05](https://github.com/user-attachments/assets/0ba9ddee-cf40-43c6-ba0d-6f9c7f1930d3)

**Comment by hpvd** [comment]
when removing the documentmetadata from pdf tagging project,
more meta data is shown in texworks pdf but not
- title
- author

**Comment by u-fischer** [comment]
In PDF 2.0 the /Info dictionary in the trailer of the PDF is deprecated. Metadata should be added as XMP-metadata (and there are added in the example).
When you use a standard like A-4 or UA-2 deprecated features are not allowed and so the LaTeX-code suppresses the /Info dictionary and only adds XMP-metadata.

**Comment by hpvd** [comment]
thanks @u-fischer

addition: the pdf produced with code shown in https://github.com/TeXworks/texworks/issues/1063#issue-2563678854
fully passes pdf validation on https://dev.verapdf-rest.duallab.com/
