### ISSUE TITLE
TeXworks editor eats non-breaking spaces

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#253]
```
Create a text file containing a single “ ” (that’s U+00A0).
Open it in TeXworks (latest version of TeXworks on Windows 7), add a
character at the end to enable the save command, and save. The non-breaking
space “ ” (U+00A0) changes to a regular space “ ” (U+0020).

This wreaks havoc with the command I’ve been using to treat non-breaking
spaces in .tex source as non-breaking spaces:

\catcode` =\the\catcode`~ \let =~

TeX does not like having U+0020 redefined :(

(TeXworks also does a gratuitous LF-to-CRLF rewrite of the file. It’s not a
huge deal but I mention it in case it is related to the main issue.)
```

Original issue reported on code.google.com by `neit...@gmail.com` on 11 Dec 2009 at 3:31

**Comment by stloeffler** [comment]
The issue with saving has been fixed now (for Qt >= 5.9). Copying/pasting is handled entirely by Qt, so this is a Qt issue - most probably related to the fact that [QTextDocument::toPlainText()](https://github.com/qt/qtbase/blob/e650ea323f5d7146caa020b69d22ace437609883/src/gui/text/qtextdocument.cpp#L1208-L1210) manually replaces nbsp with "regular" spaces.
