### ISSUE TITLE
drag-drop text turns Chinese

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#372]
```
What steps will reproduce the problem?
1. select text (in HTMLKit (free 292 http://www.htmlkit.com/download/)
2. drag drop selected text (holding Crtl key down) it into Tw Edior
3.

What is the expected output? What do you see instead?

plain ascii type text
Chinese characters!

What version of the product are you using? On what operating system?
Tw 0.3 ver 650 Win Xp Pro sp3

Please provide any additional information below.

jpeg image and txt notepad .txt copy of text in question
```

Original issue reported on code.google.com by `paul.a.norman` on 27 May 2010 at 5:08

Attachments:
- [dragDropText.jpg](https://storage.googleapis.com/google-code-attachments/texworks/issue-372/comment-0/dragDropText.jpg)
- [dragDropText.jpg.txt](https://storage.googleapis.com/google-code-attachments/texworks/issue-372/comment-0/dragDropText.jpg.txt)

**Comment by stloeffler** [comment]
Closed as it refers to a heavily outdated version of Tw.
