### ISSUE TITLE
Feature request: Kill lines

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#39]
```
A short cut for killing lines would be nice: this is handy to get rid of
blank spaces and also when removing large blocks.  Ctrl-K is often used for
this. 

```

Original issue reported on code.google.com by `joseph.w...@morningstar2.co.uk` on 24 Sep 2008 at 4:42

**Comment by stloeffler** [comment]
This can easily be implemented as a script (see, e.g., stloeffler/TeXworks-scripts@986bdf3)
