### ISSUE TITLE
Remove placeholders (bullets) in the completion

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#449]
```
As of myself, I'm spending extra time manually erasing these placeholders 
(bullets) every time I use the completion.

Did you ran a survey on how popular this feature is? It may actually slow you 
down, as it is in my case.
```

Original issue reported on code.google.com by `bryn...@gmail.com` on 8 Dec 2010 at 12:39

**Comment by josephwright** [comment]
Suggest this is closed: TeXworks uses bullets and in https://github.com/TeXworks/texworks/issues/813 I am seeking to tidy them up anyway.

**Comment by stloeffler** [comment]
By now, completion files (and similar provided files) are updated automatically, provided they have not been changed by the user since they were installed/last updated automatically.
