### ISSUE TITLE
Syntax highlighting disappears one second after document is opened

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#559]
```
What steps will reproduce the problem?
1. Open a .tex document.  
2. See that there is syntax highlighting.  
3. Wait 1 second.  
4. Watch it disappear, i.e. the text remains but the highlighting is gone.  

OS X 10.6.8
TexWorks v0.4.3 r.858

```

Original issue reported on code.google.com by `rger...@gmail.com` on 10 Feb 2012 at 11:24

**Comment by stloeffler** [comment]
This issue pertains to a long-outdated version of TeXworks and Qt. Therefore it will be closed for now. Should the issue persists in the latest version, it can be reopened of course.
