### ISSUE TITLE
documents are not restored on linux

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#581]
```
On opensuse 12.2factotory, kde trunk... texworks does not restore the documents.

open a document...
logout the session... login again... and texworks will be restored with an 
Untitled document.

regards,
Alin
```

Original issue reported on code.google.com by `alinm.el...@gmail.com` on 20 May 2012 at 5:39

**Comment by stloeffler** [comment]
This issue pertains to a long-outdated version of TeXworks and Qt. Therefore it will be closed for now. Should the issue persists in the latest version, it can be reopened of course.
