### ISSUE TITLE
"! I can't find file `test.tex'" when compiling

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#663]
```
Hi there, thanks a lot for the help, I`m a bloody beginner and try to keep it 
short. Have a nice day :)

What steps will reproduce the problem?
1. open texworks, CTRL+Shift+N
2. basic LaTeX doc -> letter
3. "compile"(?) as pdfLaTeX OR pdfTeX or LuaTex .....

What is the expected output? What do you see instead?
Some sort of (empty) document


What version of the product are you using? On what operating system?
TexWorks: 0.4.5 r1280 official
Win7 Prof 64bit SP1 english
TexLive was completely installed (newest version, definitely up to date says 
package manager)


Please provide any additional information below.

Problem is pretty universal. Many things dont work, also Texmaker gives me a 
bunch of errors. I installed TexLive completely a second time.

Console spits out the following.

"This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014/W32TeX) 
(preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `test.tex'.
<*> test.tex
            
(Press Enter to retry, or Control-Z to exit)
Please type another input file name: "
```

Original issue reported on code.google.com by `goR...@gmail.com` on 19 Jun 2014 at 10:43

**Comment by Rhubarbmunch** [comment]
I also have the same problem.  

1. It is just a hello-world latex file called fred.tex.
2. It is not in a directory run by Dropbox
3. The file is definitely there, and has rw permission for me.
4. latex (livetex I belive) is not finding the file, even though I issue a command-line
   call :  latex fred  or latex fred.tex (makes no difference) from that directory.

Here is the output: 
myprompt>  pdflatex fred.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `fred.tex'.
<*> fred.tex
            
(Press Enter to retry, or Control-D to exit)
Please type another input file name: 

Any clues from anyone?

**Comment by Rhubarbmunch** [comment]
More data:  If instead I type

pdflatex ./fred.tex

then it works (i.e. note the ./ ).  This is not much use if I use texworks, since I cannot
then specify the ./
Anyway, it stlll fails, because it does not find article.cls
(My first line is documentclass{article}).

I find this file at 
./share/texlive/texmf-dist/tex/latex/base/article.cls

What is going on?  Whey does it not know where to find files,
even in the current directory?  

I have removed and reinstalled texlive, but to no avail.
