### ISSUE TITLE
Customize editor text cursor

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TeXworks/texworks#668]
```
version 0.5 r952 ubuntu 12.04 LTS

The text editor cursor is hard to see, especially on a small laptop. I know how 
to change cursor--but only for gtk, not qt apps.

Is the cursor hardcoded or changable?  Is this a texworks or qt issue?

Thanks for a great piece of software!
```

Original issue reported on code.google.com by `charlesl...@gmail.com` on 10 Sep 2014 at 6:11

**Comment by huftis** [comment]
If someone decides to implement a better caret, you might want to take a look at the implementation used in Konsole. It implements three different possible caret renderings. See TerminalDisplay::drawCursor() at https://lxr.kde.org/source/kde/applications/konsole/src/TerminalDisplay.cpp

**Comment by nkhabarov** [comment]
Just found a way of solving this issue (on Windows 7). I have set the thickness of the blinking cursor via the Control Panel as suggested here: https://www.howtogeek.com/194095/how-to-change-the-blinking-windows-keyboard-cursor-thickness/ So, now it's much easier to see the cursor in TeXworks when jumping to the source from the TeXworks PDF viewer. The downside, however, is that in some other applications (not all) the cursor is also of that size.

**Comment by gpl34** [comment]
I confirm: on Linux, on a HiDPI screen, the text cursor is barely visible. This leads to unwanted selection or wrong selection all the time. I looked into qss to see whether it's possible to style this globally, unfortunately, it's not: [QT bug report](https://bugreports.qt.io/browse/QTBUG-30326).
