### ISSUE TITLE
wiki: Homebrew instructions should be slightly tweaked

### ISSUE THREAD

**Issue by mc10** [TeXworks/texworks#702]
On the [building on Homebrew page](https://github.com/TeXworks/texworks/wiki/Building-on-Mac-OS-X-%28Homebrew%29), for the line `brew install poppler --with-qt4 --enable-xpdf-headers`, `--with-qt4` should be replaced with `--with-qt`, as the former is deprecated.

**Comment by stloeffler** [comment]
Thanks - changed.
