### ISSUE TITLE
Integrate Citation Databases into Bibtex

### ISSUE THREAD

**Issue by ffanatic13** [TeXworks/texworks#708]
Hey guys,

I work in the field of mathematics and most of our citations can be taken from only a few places (math sci net and axriv for instance).  I sat down and wrote out a script in python which would do textual analysis on these websites and automatically generate a .bib file with the citations listed.  This seems like it would be an awesome contribution to your work if you could consider doing this for all the major citation databases.  

I don't know if you guys use python for your work or I would submit it to your codebase.  At very minimum, I would love the critique of style.

Dan

**Comment by stloeffler** [comment]
I think this is beyond the scope of Tw, particularly as far as the current status of development of Tw is concerned. In particular, there are other programs dedicated to the management of BiBTeX databases, such as for example [JabRef](http://jabref.sourceforge.net/).

That said, I am interested in seeing what you did as I, too, use Python and citations quite extensively. Maybe you could put it on your own github repository, or send it to me via email?
