### ISSUE TITLE
Compile while PDF opened leads to corrupted file

### ISSUE THREAD

**Issue by solehill** [TeXworks/texworks#709]
I'm not entirely sure what the source of the error is but when a PDF is open in texworks and pdflatex is run, the PDF file is overwritten with a version that cannot be opened. Compiling while the PDF is not open in texworks on the other hand gives the expected result. 

The error happens on a up-to-date Miktex installation in Windows 10 and with a minimal error.tex file such as:

\documentclass{article}
\begin{document}
Test
\end{document}

Running pdflatex on this file works fine. Running first texworks error.pdf and then pdflatex error.pdf results in a PDF file that, when later opened in  Adobe Acrobat Reader, results in the error "Cannot extract the embedded font 'XGWFBW+CMR10'. Some characters may not display or print correctly." The document is simply blank in both Acrobat and Texworks.

**Comment by stloeffler** [comment]
Closed because it refers to an outdated version of both Tw and its libraries.
