### ISSUE TITLE
keyboard sequence <alt-gr>+<s> error 

### ISSUE THREAD

**Issue by brk01** [TeXworks/texworks#710]
Texworks does not process keyboard sequence <alt-gr>+<s> properly. In my case, this sequence should type the polish letter <ś> but Texworks attempts to save the file (ctrl+s) instead. Moreover the latex sequence \’s cannot be used to produce <ś> either, because a Texworks macro replaces \’s by \rq{}s automatically.

**Comment by 36451** [comment]
Yes. Texworks doesn't handle alt-gr + s correctly. 
There is a workaround - you can press alt-gr+win+s which produces correct output, but it's a very anyoing bug.

**Comment by UniqMartin** [comment]
This is not really a bug in TeXworks but a limitation in the Qt framework TeXworks is using for its cross-platform user interface. Qt unfortunately doesn't distinguish between alt-gr + letter and ctrl + alt + letter.

There's a relatively simple workaround though, namely disabling the offending shortcut(s). For this particular example, one would have to create a file named `shortcuts.ini` with the following contents (the second line is not strictly needed, but I like to disable that shortcut, too):

```
actionSave_All =
actionSave_As =
```

(The TeXworks manual installed with every TeXworks installation has more detail in its “Keyboard Shortcuts” section of the “Customizing TeXworks” chapter. It also explains where to put that file.)
