### ISSUE TITLE
Compile from source error

### ISSUE THREAD

**Issue by tuchwando** [TeXworks/texworks#711]
I'm trying to compile TexWorks from source for CentOs 6.7...  I got to running "make" and there's an error:

[ 88%] Building CXX object src/CMakeFiles/texworks.dir/PDFDocument.cpp.o
/home/pfletcher/Downloads/texworks-0.4.6-20150403-git_c29723a/src/PDFDocument.cpp: In member function ‘void PDFDocument::doFindAgain(bool)’:
/home/pfletcher/Downloads/texworks-0.4.6-20150403-git_c29723a/src/PDFDocument.cpp:1837: error: no matching function for call to ‘Poppler::Page::search(QString&, double&, double&, double&, double&, Poppler::Page::SearchDirection&, Poppler::Page::SearchMode&)’
/usr/include/poppler/qt4/poppler-qt4.h:475: note: candidates are: bool Poppler::Page::search(const QString&, QRectF&, Poppler::Page::SearchDirection, Poppler::Page::SearchMode, Poppler::Page::Rotation) const
make[2]: *** [src/CMakeFiles/texworks.dir/PDFDocument.cpp.o] Error 1
make[1]: *** [src/CMakeFiles/texworks.dir/all] Error 2
make: *** [all] Error 2

Any advice for how I can get past it?  Have I missed installing a certain dependency, or is one of my installed libraries too old?

Thanks in advance!

**Comment by stloeffler** [comment]
Hi,

On 30.10.2015 16:05, tuchwando wrote:
>
> I'm trying to compile TexWorks from source for CentOs 6.7... I got to
> running "make" and there's an error:
>
> [ 88%] Building CXX object src/CMakeFiles/texworks.dir/PDFDocument.cpp.o
> /home/pfletcher/Downloads/texworks-0.4.6-20150403-git_c29723a/src/PDFDocument.cpp:
> In member function ‘void PDFDocument::doFindAgain(bool)’:
> /home/pfletcher/Downloads/texworks-0.4.6-20150403-git_c29723a/src/PDFDocument.cpp:1837:
> error: no matching function for call to
> ‘Poppler::Page::search(QString&, double&, double&, double&, double&,
> Poppler::Page::SearchDirection&, Poppler::Page::SearchMode&)’
> /usr/include/poppler/qt4/poppler-qt4.h:475: note: candidates are: bool
> Poppler::Page::search(const QString&, QRectF&,
> Poppler::Page::SearchDirection, Poppler::Page::SearchMode,
> Poppler::Page::Rotation) const
>

Hm, this is weird. According to the documentation
(http://people.freedesktop.org/~aacid/docs/qt4/classPoppler_1_1Page.html#a1fc6148409e3f2f384d0241c2628e409),
this function is available since poppler 0.14 (which dates back to 2010).

> Any advice for how I can get past it? Have I missed installing a
> certain dependency, or is one of my installed libraries too old? 

Maybe - what version of poppler are you using?

HTH
Stefan

**Comment by UniqMartin** [comment]
CentOS 6.7 is stuck with Poppler 0.12.4, so that's why it doesn't have the overload used by TeXworks. (Poppler 0.14.0 was released in 2010 and the most recent release is 0.38.0!)

**Comment by tuchwando** [comment]
OK. Thanks for the replies! I have been using TexWorks under Windows for a
while, and love it! Now I've got a linux machine at work, and they run
CentOS...

Looks like I will need to try updating poppler-devel... May need to compile
it from source too. Any advice on which version? Something close to 0.12.4
but greater than 0.14.0?

Thanks again,

Patrick
