### ISSUE TITLE
Can't download from Distribution site (Google Drive)

### ISSUE THREAD

**Issue by matthewdeanmartin** [TeXworks/texworks#712]
Google Drive (not the browser or workstation antivirus) doesn't allow downloading the windows installer.

"Sorry, this file is infected with a virus
Only the owner is allowed to download infected files."

link for ref. https://drive.google.com/uc?id=0B5iVT8Q7W44pOTZpWlQxbzIzd2M&export=download

**Comment by stloeffler** [comment]
AFAICT, this is an error on Google's side. I requested a review of the file.
Meanwhile, the release files can also be downloaded from https://github.com/TeXworks/texworks/releases

**Comment by vassifht** [comment]
Is there somewhere 0.4.6 for OS X?

**Comment by stloeffler** [comment]
The Google Drive downloads should work again.

Regarding OS X: I am afraid there is no official build ATM. I don't have a Mac to build on myself, and Apple's license agreements are very restrictive. I am currently looking into using [Travis CI](http://travis-ci.org/) for automated building, so there is hope for timely OS X builds in the near future...
