### ISSUE TITLE
TeXworks randomly crashes upon startup

### ISSUE THREAD

**Issue by devreal** [TeXworks/texworks#714]
I see random crashes of TeXworks during startup when giving a tex-file as the only argument. The stack trace from the core file looks like: 
```
#0  QWidgetPrivate::showChildren (this=this@entry=0x2044d60, spontaneous=spontaneous@entry=false) at kernel/qwidget.cpp:7854
#1  0x00007f718937591f in QWidgetPrivate::show_helper (this=this@entry=0x2044d60) at kernel/qwidget.cpp:7503
#2  0x00007f71893776c4 in QWidget::setVisible (this=0x1fb78c0, visible=<optimized out>) at kernel/qwidget.cpp:7778
#3  0x00007f718937589e in show (this=0x1fb78c0) at ../../include/QtGui/../../src/gui/kernel/qwidget.h:497
#4  QWidgetPrivate::showChildren (this=this@entry=0x15c9030, spontaneous=spontaneous@entry=false) at kernel/qwidget.cpp:7866
#5  0x00007f718937591f in QWidgetPrivate::show_helper (this=this@entry=0x15c9030) at kernel/qwidget.cpp:7503
#6  0x00007f71893776c4 in QWidget::setVisible (this=0x161c3e0, visible=<optimized out>) at kernel/qwidget.cpp:7778
#7  0x00000000004adc04 in TeXDocument::loadFile(QString const&, bool, bool, QTextCodec*) ()
#8  0x00000000004aed92 in TeXDocument::TeXDocument(QString const&, bool) ()
#9  0x00000000004af144 in TeXDocument::openDocument(QString const&, bool, bool, int, int, int) ()
#10 0x0000000000467852 in main ()
```

The version I used is TeXworks 0.5r1350 (Debian), Qt version is 4.8.6. Is this a known issue? Please let me know if you need additional information.

**Comment by stloeffler** [comment]
As it seems to occur when opening a file, it looks a bit similar to #497 although the stack trace is different.
In any case, the build you mention seems to be over 2 years old. Could you try with a more recent version? (current deb packages (built for Ubuntu) are available at https://launchpad.net/~texworks/+archive/ubuntu/ppa)
Other things that might be worth investigating:
 - Does diisabling syntax highlighting in the preferences before opening a file help?
 - Does this happen for all files (including minimal examples)?
 - Does this happen when a) Tw is not running and you click on a .tex file; b) Tw is just started (with an empty window) and the .tex file is loaded into that window; c) Tw is running, the current window is not the default, empty window, and consequently opening a .tex file opens a new window

**Comment by devreal** [comment]
Thanks a lot for your quick reply. I didn't realize that Linux Mint is shipping such an old version of TeXworks. I installed the current version from the ppa and haven't seen a crash in a few tests. I will keep an eye on it.
