### ISSUE TITLE
Line feeds not working properly

### ISSUE THREAD

**Issue by hungaborhorvath** [TeXworks/texworks#729]
When a tex file created in windows is later opened by texworks in linux, it opens with CRLF line feed, and it works perfectly. I can see CRLF in the status bar. 

After editing this file in linux with texworks, and sending it back to the windows machine, they see double line breaks, i.e. an empty line after each proper line. 

If I switch on the linux machine to LF, save the file with LF line feeds, then send the resulting file to the windows machine, the file looks like as it is supposed to. 

I am sorry for the noob question, but is this the intended behaviour? I thought that CRLF was for recognizing windows type line breaks, but I do not see why it breaks if transferred back to a windows machine. 

Alternatively, is there a way where I can set that all my files should be saved with LF (linux style) line feeds after opened by texworks? 

Thanks.

**Comment by stloeffler** [comment]
Thanks for reporting. This is definitely not intended behavior. Unfortunately, I can't reproduce it on my Linux machine...

1. Which version of TeXworks do you use (on Linux and on Windows)?
2. Which Linux and which Windows do you use
3. Could you send me example .tex files (both after creation on Windows and after editing on Linux)?

**Comment by hungaborhorvath** [comment]
[sample1.txt](https://github.com/TeXworks/texworks/files/182477/sample1.txt)
[sample2.txt](https://github.com/TeXworks/texworks/files/182482/sample2.txt)
[sample2_LF.txt](https://github.com/TeXworks/texworks/files/182484/sample2_LF.txt)
[sample3.txt](https://github.com/TeXworks/texworks/files/182488/sample3.txt)
[sample3_LF.txt](https://github.com/TeXworks/texworks/files/182489/sample3_LF.txt)

I have attached 5 files, all of them tex, but with txt extension because github does not allow to upload tex files....

Anyway, sample1 is created under windows 7 using TeXstudio 3.14159265-2.6-1.40.16 (TeX Live 2015/W32TeX). I opened it on debian jessie with texworks 0.5~svn1363-5. It opened with CRLF mode automatically, and sample2 is saved using CRLF, and without problems. I also saved a version using only LF, this is sample2_LF. Then with the same windows machine and programs, both of these second samples were written, again, and now even under texworks one can see that the CRLF version has extra lines, and the LF version does not have extra lines. Both opens in CRLF mode, though.

**Comment by stloeffler** [comment]
Thanks for the sample files!

From what I can tell, sample1 and sample2 have CRLFs, whereas sample2_LF has LFs as expected.

sample3 indeed has two CRLFs per line ending, and sample3_LF has one CRLF per line ending (which accounts for the mentioned CRLF mode as well as the empty lines).
Just to clarify, were sample3 and sample3_LF created by TeXworks on Windows or by TeXStudio? As sample2 seems to be correct, I suppose the problem lies somewhere with whatever Windows program was used to open sample2 and create sample3 from it...

**Comment by hungaborhorvath** [comment]
sample3 and sample3_LF were created from sample2 and sample2_Lf, respectively, using windows 7 with the same version of TeXstudio, and not texworks. Just to note: when they open the file sample2.tex, they already see it with the extra line feeds. Some of my other students also complained about this problem with my files. They also use windows, I am not sure what program, but can ask them if it helps.

BTW, it would be enough for me if there was a default line feed mode somewhere in the options or in the config files, so I could choose that texworks always saves every file with LF everywhere. Those seem to be properly readable with the windows programs of my students.

**Comment by hungaborhorvath** [comment]
Apparently, sample2 opens properly with windows notepad.... So it might be a texstudio issue.... I will report it with them.

**Comment by stloeffler** [comment]
OK - as I said above, sample2 and sample2_LF seem to be properly formatted, so TeXworks on your Linux machine behaves as it should. Why those files are treated incorrectly by TeXStudio I don't know.

Regarding the default: I'm a bit reluctant to automatically change the line endings of all files (to a default value). This could break a lot of things (including, e.g., the display of the file on Windows if you always save as LF, version control systems, programs for comparing files such as `diff`, etc.). That said, if you want to mass-convert files on Linux, there are simple tools for that like `dos2unix` and `unix2dos`.
