### ISSUE TITLE
jump to source not working

### ISSUE THREAD

**Issue by drgabosc** [TeXworks/texworks#736]
_Steps to reproduce the problem_:

1. Typeset a file.tex
2. In file.pdf left click on x word "Jump to Source"
3. 

_Expected output_: file.tex with x word selected.

_Actual output_: kind of beginning of file.tex

_TeXworks version_: 0.6.0
_TeXworks obtained from_:
_Operating system_: Windows 10 and 7

_Please provide any additional information below_:

**Comment by qwertzdenek** [comment]
I can confirm this issue. Freshly compiled with QT5 from source on ArchLinux.
