### ISSUE TITLE
Please add Biber support

### ISSUE THREAD

**Issue by ShikiSuen** [TeXworks/texworks#737]
_Steps to reproduce the problem_:
1. Use "biblatex-chicago" package in your ".tex" file.
2. Add the definition `%!BIB TS-program = biber` to the top of the content of your ".tex" file.
3. Use TeXWorks 0.6.0 offered by https://github.com/TeXworks/texworks/releases

_Expected output_:
All footcites and bibliography contents are correctly written to the output PDF file.

_Actual output_:
Nothing.

_TeXworks version_: 0.6.0
_TeXworks obtained from_: https://github.com/TeXworks/texworks/releases
_Operating system_: OS X El Capitan 10.11.4 & Windows 10 10586.164

_Please provide any additional information below_:
The "biblatex-chicago" package is currently **the only way** to use the **latest** version of "Chicago Manual of Tyle" thoroughly in LaTeX, and this package depends on biber. I know some people could hack some configurations to let it work. However, such approaches are not friendly to most users. I know most TeX IDE developers have discriminations that they think BibTeX is everything (ref: TeXPad for iOS, its UI description of this looks insulting even though it actually supports biber.), leading to their default settings which made people feel hard to use Biber. However, I still have my hope on TeXWorks.

**Comment by josephwright** [comment]
On 08/04/2016 22:53, 孫 志貴 wrote:
> _Steps to reproduce the problem_:
> 
> 1. Use "biblatex-chicago" package in your ".tex" file.
> 2. Add the following definition to the top of the content of your ".tex" file.
> `%!BIB TS-program = biber`
> 3. Use TeXWorks 0.6.0 offered by https://github.com/TeXworks/texworks/releases
> 
> _Expected output_:
> All footcites and bibliography contents are correctly written to the output PDF file.
> 
> _Actual output_:
> Nothing.
> 
> _TeXworks version_: 0.6.0
> _TeXworks obtained from_: https://github.com/TeXworks/texworks/releases
> _Operating system_: OS X El Capitan 10.11.4 & Windows 10 10586.164
> 
> _Please provide any additional information below_:
> The "biblatex-chicago" package is currently the only way to use the **latest** version of "Chicago Manual of Tyle" thoroughly in LaTeX, and this package depends on biber. I know some people could hack some configurations to let it work. However, such approaches are not friendly to most users. I know most TeX IDE developers have discriminations that they think BibTeX is everything (ref: TeXPad for iOS, its UI description of this looks insulting even though it actually supports biber.), leading to their default settings which made people feel hard to use Biber. However, I still have my hope on TeXWorks.

TeXworks does not try to automatically run any bibliography step, unlike
TeXshop, where "! BIB TS-Program" comes from. As such, in TeXworks you
are expected to either

- Manually run any secondary processes or
- Manually select and run a script

TeXworks does have BibTeX as a 'ready to go' bibliography program, and
using this as a model adding Biber is trivial: see
http://tex.stackexchange.com/a/154767/73.

Joseph

**Comment by ShikiSuen** [comment]
@josephwright It is trivial to me but not to most users. I am thinking of publicize the LaTeX to those students and teachers in our entire Faculty. However, most of them are not so good at doing such troubleshootings. The ideal way is that they get the TeXLive distribution, install it, and it gets ready-to-use. In such case, I don't think it is a big trouble to let TeXWorks have a built-in preset for Biber (incl: XeLaTeX->Biber->XeLaTeX). Please let me know if this is really a big trouble to you team, and I will give up TeXWorks in such case.

**Comment by ShikiSuen** [comment]
I have found a better preset definition (one-way compilation), but it require that all files shall be written in UTF-8:

## XeLaTeX
NAME: `Latexmk-XeLaTeX`
PROGRAM: `latexmk`
Parameter:
```-e
$pdflatex=q/xelatex %O -synctex=1 %S/
-e
$biber=q/biber %O --bblencoding=utf8 -u -U --output_safechars %B/
-norc
-gg
-pdf
$fullname
```

**Comment by josephwright** [comment]
I would welcome addition of Biber to the list of 'standard' engines in TeXworks: I was pointing out mianly that (by design) TeXworks focusses on 'one tool at a time'. (I like this approach, but of course others find alternatives helpful. There are lots of IDEs.)

**Comment by stloeffler** [comment]
Biber was added to the standard engine list. However, please note that this only takes effect for new installations of TeXworks (or if you never made any changes to the engine list, i.e., there is no file <resources>/configuration/tools.ini).

**Comment by ShikiSuen** [comment]
Thanks. I appreciate your efforts towards this feature request.
