### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by jt5390** [TeXworks/texworks#741]
No syntax highlighting option available. No idea how to fix. 

_TeXworks version_:0.6.0
_TeXworks obtained from_:https://www.tug.org/texworks/
_Operating system_: OS X El Capitan

I downloaded the newest version of Texworks and syntax highlighting latex is not available.

**Comment by stloeffler** [comment]
Am I correct in assuming that under Format > Syntax Highlighting, you only have "None"?
What paths are given in Help > Settings and Resources... (should include `~/Library/TeXworks/`)? Do those folders exist and are they writable to your user?

Background: Tw initially copies some resources (including syntax highlighting definition) to that folder so the user can adapt them to his needs. If that copying does not succeed, Tw will assume the user deleted/does not want those files. You could possibly work around this by manually creating abovementioned folders and manually putting the files from https://github.com/TeXworks/texworks/tree/master/res/resfiles in there - but of course that shouldn't be necessary...

**Comment by stloeffler** [comment]
Closed due to inactivity and because the issue refers to an outdated version of Tw.
