### ISSUE TITLE
ZWNJ not working

### ISSUE THREAD

**Issue by bateni** [TeXworks/texworks#747]
_Steps to reproduce the problem_:
1. Start a Farsi text, e.g.: می
2. Type ZWNJ (shift+space on standard Persian keyboard)
3. Then continue with the text, e.g., خواهم

_Expected output_:
می‌خواهم

_Actual output_:
میخواهم

_TeXworks version_: Version 0.6.0 (travis-ci) [r.e6d231b, 4/3/16 5:34 AM]
_TeXworks obtained from_: TeXworks website
_Operating system_: Mac OS X

_Please provide any additional information below_:

The cause is a long-standing bug in new Qt versions.
https://bugreports.qt.io/browse/QTBUG-42074
Until the bug is fixed in Qt, there are some simple workarounds for patching the code to make it work.

https://qt.gitorious.org/qt/qtbase/source/9fd2edb6da5f1f6d644cd7c3f35aebe3e88beee2:src/widgets/widgets/qwidgetlinecontrol.cpp#L1852
https://stackoverflow.com/questions/24710704/override-keyboard-map-in-qt-application

It is very hard to type any meaningful Persian text without ZWNJ.  Thanks a lot for your attention!

**Comment by bateni** [comment]
I just built from the source, and it seems to be working fine.
Version 0.7 (personal) [r.07e22ef, 5/30/16 3:45 PM]

**Comment by agn-7** [comment]
In Linux, it simply works with <kbd>Shift</kbd> + B
