### ISSUE TITLE
<Alt> + <Left Arrow> does not trigger rerendering

### ISSUE THREAD

**Issue by denniske** [TeXworks/texworks#748]
_Steps to reproduce the problem_:
1. Create pdf with link on page 1 to page 5
2. Render
3. View page 1 in the previewer and click on link to page 5
4. Change pdf content of page 1
5. Render
6. Press <Alt> + <Left Arrow> in the previewer

_Expected output_:

Rendering new content of page 1

_Actual output_:

Showing the page 1 as it was before rerendering

_TeXworks version_: 0.6.1
_TeXworks obtained from_: Official download site
_Operating system_: Windows 10

_Please provide any additional information below_:

**Comment by stloeffler** [comment]
Hi. Thanks for the report. Unfortunately, I can't reproduce this with the current version on Linux. As links are annotations, maybe this has been affected by #746? Can you test with the [latest development version](https://bintray.com/texworks/Windows-latest/TeXworks-for-Windows%3Alatest/view)?

**Comment by stloeffler** [comment]
Closed due to inactivity and irreproducibility.
