### ISSUE TITLE
Seg fault during normal editing

### ISSUE THREAD

**Issue by charlesnix** [TeXworks/texworks#749]
When editing documents, seemingly randomly, TeXworks crashes.

The following error from the most recent occurrence appears in kern.log:
Jun 16 14:51:27 harp kernel: [521046.629877] texworks[19079]: segfault at 0 ip 013b8624 sp bfe939e0 error 4 in libQtGui.so.4.8.1[fdf000+aaa000]

Ubuntu 12.04 LTS
TeXworks Version 0.7 (launchpad) [r.74b30cc, 5 May 2016 02:29:43]
obtained from TeXworks PPA

It looks like this is coming from Qt, but I don't know how to set up a backtrace or get other needed information.  I will be glad to do whatever I can to help if someone can let me know what is needed.
C Nix

Additional information--because it happened again 10 minutes later:  I had deleted a large block of text and was holding the "down arrow" key to scroll down the page when it happened.

**Comment by stloeffler** [comment]
This sounds a lot like #469, unfortunately...

**Comment by stloeffler** [comment]
Qt4 is no longer used.
