### ISSUE TITLE
non-breakable space since TeXworks 0.4.6 released!

### ISSUE THREAD

**Issue by Farschaad** [TeXworks/texworks#750]
Dear Sir/Madam,

I've been using texworks for a long time and due to my nationality, I use to type in Persian language which is a bidirectional one.  In previous versions of TeXWorks prior to TeXworks 0.4.6, non-breakable space could be inserted to the text simply by pressing Shft+Space. However, from TeXworks 0.4.6 and on, non-breakable space can not be inserted in any case. Since non-breakable space is quite common in Persian (and Arabic) articles (just as common as space), I would like to ask you if you just kindly reactivate non-breakable space in TeXWorks new version.

_Steps to reproduce the problem_:
1.  Type a letter in Persian like می
2. Insert Shift+Space between the two characters
3. Then it should become م‌ی  but it becomes م ی (with an extra space in between)

_Expected output_:
م‌ی

_Actual output_:
م ی

_TeXworks version_: from 0.4.6 on
_TeXworks obtained from_: texlive 2015 installer (not seen in texlive 2014)
_Operating system_: windows and linux

_Please provide any additional information below_:

**Comment by stloeffler** [comment]
Thank you for your report. To me, this sounds a lot like a bug in the Qt library which TeXworks uses to handle text input (see e.g. https://bugreports.qt.io/browse/QTBUG-56538).
Can you possibly check which versions of Qt your copies of pre-0.4.6 and post-0.4.6 TeXworks use (from Help > About TeXworks...)?

**Comment by stloeffler** [comment]
Closed due to inactivity, because it was reported against an outdated version of Tw, and because a related Qt bug has been fixed in the meantime.
