### ISSUE TITLE
TeXworks Not Included with MacTeX

### ISSUE THREAD

**Issue by mikeoucsd** [TeXworks/texworks#754]
On [your website](https://www.tug.org/texworks/) it says, "Note that TeX Live (since version 2009) and MiKTeX (since version 2.8) both include TeXworks for MS Windows, and the MacTeX release (since version 2009, corresponding to TeX Live 2009) includes TeXworks for Mac OS X."

But MacTeX 2016 does not come with TeXworks.  It would be great if you could talk to the MacTeX folks and get TeXworks included in MacTeX, but if you can't you should probably remove that information from your website.  Thanks.

**Comment by stloeffler** [comment]
Thanks for the report. I corrected the website in TeXworks/website@04ba1c34090a50e1732f9be1274e9a9ca64e3573
Hopefully MacTeX will support TeXworks again at some point, but thanks to the travis-ci integration, up-to-date builds for Mac are now available (as described on the website).
