### ISSUE TITLE
Unicode hexadecimal code composition doesn't work

### ISSUE THREAD

**Issue by Stemby** [TeXworks/texworks#758]
_Steps to reproduce the problem_:
1. Run TeXworks
2. Hold <kbd>Ctrl</kbd> + <kbd>⇧ Shift</kbd> and type <kbd>u</kbd>

_Expected output_:
Underlined _u_ should appear.

_Actual output_:
Nothing.

_TeXworks version_: 0.6.1
_TeXworks obtained from_: official Debian package (from Debian repos)
_Operating system_: Debian testing

_Please provide any additional information below_:
This is a feature request: hex input is not implemented in X.Org, but it's very useful and I think it should be provided by TeXworks.

See also [here](https://en.wikipedia.org/wiki/Unicode_input#In_X11_.28Linux_and_other_Unix_variants.29).

Thanks!

Carlo

**Comment by stloeffler** [comment]
Works in recent version.
