### ISSUE TITLE
Quotation marks problem

### ISSUE THREAD

**Issue by skn89** [TeXworks/texworks#760]
Hello,

it is about the symbols " and ' that I use for German characters while typesetting text in the editor. This problem occures on my PCs and may normally have a solution, but, I have not found any untill now. I have tried different preferences of the programm, as much as different TeX editors. This one appears only in TeXworks. 

_Steps to reproduce the problem_:

1. A good question. Maybe, get two PCs runnings Windows 10 and install MiKTeX on the both.
2. Use a Cloud or some other storage medium for storing documents.
3. Try to work at one document, save it in the storage, and transmit to another PC. Open and text the quotation marks.

_Expected output_:

After I have finished working on the document at one PC, I move it to the Cloud and download it from an another one. After the document has been opened I want to continue the work.

_Actual output_:
I cannot use " and ' symbols anymore. Either I get two ' symbols hitting the key only one time, or I get \flqq\frqq by hitting the key only one time.  And, I cannot do anything to restore a desired output. Sometimes it helps to create a new TeXworks document and copy-paste the code text into it. But normally it does not work. Some other time the problem does not occure.

Please refer to my issue on
http://tex.stackexchange.com/questions/335749/strange-quotation-marks-wrong-encoding-no-special-german-symbols
for the whole description. 

_TeXworks version_: 0.6.1
_TeXworks obtained from_: https://miktex.org/
_Operating system_: Windows 10 64-bit

_Please provide any additional information below_:

I would be glad for a solution of the issue. I like TeXworks and would like to work in it further. But, I cannot use the program for many computers I have, as workng at some document I cannot be sure that I will be able to continue the work at a different computer.

Thank you.

**Comment by stloeffler** [comment]
This is (probably) a feature, not a bug ;). It allows you quickly insert TeX-style quotation marks. For any given document, it can be configured (and turned off) under Format > Smart Quotes. The default value (which should be used for new documents) can be changed under Edit > Preferences... > Editor > Smart quotes mode (note, however, that this does value is not automatically applied to "old" documents).

Does this solve your problem?

**Comment by skn89** [comment]
Thanks, Stefan! That really solves it.

I was confused about it, because smart quotes were turned off in the preferences on the both computers. and I still got smart quotes instead. I will figure out if the format changes by the transfer or because of my preferences.

Thank you very much for the explanation!
