### ISSUE TITLE
Rendering messed up

### ISSUE THREAD

**Issue by dr-stringfellow** [TeXworks/texworks#761]
Since a couple of weeks, the rendering in the pdf preview seems to be messed up when I include figures in PDF format like here:

https://www.dropbox.com/s/k2m7627wyu0f7y9/Screen%20Shot%202016-11-15%20at%2019.13.51.png?dl=0

As you can see, it does not display any of the text in the graphics (like the legend labels, for instance).

Is this a known/common error, and is there a fix for this?

I am operating on OS X El Capitan

Thx

**Comment by stloeffler** [comment]
It seems as if the graphic uses (non-standard) fonts that are not embedded and TeXworks can't find them.

The PDF standard defines 14 fonts that need not be embedded. To test if TeXworks handles them correctly, please have a look at [base14-fonts.pdf](https://github.com/TeXworks/texworks/raw/master/testcases/base14-fonts.pdf) which should render as [base14-fonts.png](https://github.com/TeXworks/texworks/blob/master/testcases/base14-fonts.png).

To check if the fonts are embedded, you can use the `pdffonts` utility (if you have it) or check in TeXworks under Window > Show > Fonts. Note that embedding the fonts is always a good idea to ensure portability...
