### ISSUE TITLE
No .log, .aux, etc files produced after "pdfLaTeX+MakeIndex+BibTex" in TeXworks

### ISSUE THREAD

**Issue by Hdlh** [TeXworks/texworks#764]
_Steps to reproduce the problem_:

1. Create LaTeX source file
2. Run in TeXworks using "pdfLaTeX+MakeIndex+BibTex"

_Expected behavior_ and _Actual behavior_:

Under an earlier version, .log, .aux files etc. were produced, but not anymore. However, when running
1. pdfLaTeX
2. BibTeX
3. pdfLaTeX
4. pdfLaTeX 
(or simply pdfLaTeX once) the .log and other files are produced.

I consider this undesirable behavior, especially when not announced or documented, very confusing...

_TeXworks version_: 0.6.1 (included in MikTeX 2.9.6100 64-bit) [r.3614278, 2016-05-01 10:43]
_TeXworks obtained from_: MikTex (download from official MiKTeX site)
_Operating system_: Windows 10, but issue reproduced also under Windows 7

_Please provide any additional information below_:

The problem was noticed for a new Windows 10 laptop, but was then reproduced on another Windows 7 laptop. Older MikTeX/TeXworks versions did not have this behavior, so this is either a change or a bug, but I have not been able to find information under "Changes" on the home page http://www.tug.org/texworks/

I hope this is sufficient information, otherwise I am willing to provide more details if needed.

Note added:
I have now found out where this behavior comes from and how it can be changed:
In TeXworks, from the menu bar, do
Edit->Preferences->Typesetting;
then under 
Processing tools
click on
pdfLaTeX+MakeIndex+BibTex
then click on
Edit...
Then under 
Arguments
click on 
--clean
and then click on 
"-" 
to remove this argument. Now there is no clean-up after running "pdfLaTeX+MakeIndex+BibTex".

It would be nice if this change in the default behavior would be documented somewhere; perhaps it is, but I could not find it. Perhaps a few extra lines in Section 3.4 in the Texworks manual ("Texworks-manual.pdf") could be added, for example something like the following could be added at the end of Section 3.4:

For example, the default behavior when running "pdfLaTeX+MakeIndex+BibTex" in TeXworks is to clean up .log files and .aux files (among others). To change this behavior, in the Edit->Preferences... menu item under the Typesetting tab, select "pdfLaTeX+MakeIndex+BibTeX", then click on the Edit... button; then remove "--clean" from the argument list.

**Comment by stloeffler** [comment]
Indeed, the --clean option for texify (the MiKTeX program behind the "pdfLaTeX+MakeIndex+BibTex" tool) is [documented](https://docs.miktex.org/manual/texify.html) to "Remove all auxiliary files."

Note that the "pdfLaTeX+MakeIndex+BibTex" tool is an [addition of MiKTeX](https://github.com/MiKTeX/miktex/blob/master/Programs/Editors/TeXworks/source/src/TWApp.cpp#L921) and is not in the main TeXworks code (see [src/TWApp.cpp](https://github.com/TeXworks/texworks/blob/master/src/TWApp.cpp#L877)). As such, there is nothing I can do about it here. Please report it to the MiKTeX developers.

**Comment by Hdlh** [comment]
Dear Stefan,
Ok, thanks a lot for the information, I did not know that. I will try to
inform the MiKTeX developers of this issue.
Best regards - Henk Hollmann

2016-12-13 17:54 GMT+01:00 Stefan Löffler <notifications@github.com>:
