### ISSUE TITLE
"Open Recent" broken by compile

### ISSUE THREAD

**Issue by mtriff** [TeXworks/texworks#768]
_Steps to reproduce the problem_:

1. Open latex file
2. Click compile button
3. Go to File > Open Recent
a. If the file has finished compiling between the time you click on File and Open Recent, nothing will load
b. If the file is still compiling, click on one of the files, it will silently not load

_Expected output_:
a. The context menu of recent files should be shown
b. The file clicked on should be opened

_Actual output_:
a. The context menu for Open Recent will not appear unless you click on File again
b. The file you have clicked on will not open

_TeXworks version_: 0.6.1
_TeXworks obtained from_: [Official site](http://www.tug.org/texworks/)
_Operating system_: MacOS Sierra, 10.12.1

**Comment by stloeffler** [comment]
Is this still an issue with the most recent version of Tw?

**Comment by stloeffler** [comment]
Closed due to inactivity
