### ISSUE TITLE
Crash texworks 0.6.1 via forward search from an if-block inside an include

### ISSUE THREAD

**Issue by tensorit** [TeXworks/texworks#770]
_Steps to reproduce the problem_:

1. Use the following as an MWE main file (attached in zip):
\newif\ifUnabridged
\Unabridgedfalse

\documentclass{article}
\begin{document}
This is an MWE for causing TexWorks version 0.6.1 to crash during a forward search operation from inside an if-block of an included file. Read the source to see how to cause the crash.

\ifUnabridged
hello.  A CTRL-click on this line works fine. The same action in the following included file causes TeXWorks 0.6.1 to crash.
\fi
\include{hello}
\end{document}

2. Use the following as the included file "hello.tex" (attached in zip)
\ifUnabridged
hello.  Do a CTRL-click on this line to cause TexWorks to crash.
\fi

As indicated, do what it says on the second line of this file, and TexWorks will crash.

3. If it makes a difference, here is the system information:
Windows 10 Enterprise, version 1607, OS Build 14393.693, 64-bit, x64-based processor
[booleanCausesTexWorksToCrash.zip](https://github.com/TeXworks/texworks/files/702595/booleanCausesTexWorksToCrash.zip)

_Expected output_:
Behavior of CTRL-click from an included file should not cause crash-- it should work the same as if the contents of the included file were copied to the main tex file.

_Actual output_:

_TeXworks version_: 
_TeXworks obtained from_: 
_Operating system_: 

_Please provide any additional information below_:

**Comment by tensorit** [comment]
Forgot to leave the requested remainder of bug report:
Actual output:  CRASHES texworks

TeXworks version: 0.6.1
TeXworks obtained from: MiTeX installation (this week)
Operating system: Windows 10 Enterprise, version 1607, OS Build 14393.693, 64-bit, x64-based processor

Please provide any additional information below:

**Comment by tensorit** [comment]
Why was this closed?

**Comment by tensorit** [comment]
Nevermind. I figured out that the cause of the problem was identified and corrected. Sorry I didn't know how to use this system properly.

**Comment by tensorit** [comment]
Is there a way to receive an alert when a new version of TexWorks is released that fixes this bug?

**Comment by stloeffler** [comment]
Sorry, I forgot to write a message explaining the details.
New stable releases are typically announced on the [mailing list](http://tug.org/mailman/listinfo/texworks). In the meantime, there are regular automatic builds of the development version (that already has the fix mentioned above) - see the [TeXworks homepage](http://www.tug.org/texworks/#Online_resources).

**Comment by tensorit** [comment]
Thank you very much for your reply!  If I properly understand your suggestion, it seems that I can obtain the latest Windows development version from

https://dl.bintray.com/texworks/Windows-latest/

As these are zip files, I would much appreciate a confirmation from you that this is indeed where I need to grab the latest precompiled version that fixes my reported bug (and the name of the precompiled version if it will not be obvious when I extract the zip archive).

Keep up the excellent work!

Rebecca Brannon
Rebecca.Brannon@utah.edu<mailto:brannon@mech.utah.edu>
cell: (801) 662-8340

**Comment by stloeffler** [comment]
Yes, that's the quick way to access them. There is also a web interface (https://bintray.com/texworks/Windows-latest/TeXworks-for-Windows%3Alatest) which needs more clicks, but provides a "nicer" interface.
Anyway, after downloading the latest zip file, you should extract all files it conrains into a folder (it doesn't matter where). Then, run the one program (TeXworks.exe) in there.
Note that this does not replace your previous TeXworks version (the one that came with MiKTeX), so all shortcuts, file associations etc. will still point to the old version. Replacing the TeXworks that comes with MiKTeX is usually not recommended (as the MiKTeX maintainers made small changes to the program so they can put it in their own directory structure, etc.).

That said, you can of course update the shortcuts to point to the newly downloaded version and by using "right-click > open with" you can also update the file associations for tex files (assuming this still works "the good old way" in Windows 10).

**Comment by tensorit** [comment]
Yep, they still do things the “good old way” in Windows to change associations, so no problem with that.

I’m a weirdo who started on Macs in the 1980s, developed in Linux during the 1990s, and ended up in Windows this millennium. Sorta the opposite of everyone else. LOL.

Rebecca Brannon
Rebecca.Brannon@utah.edu<mailto:brannon@mech.utah.edu>
cell: (801) 662-8340
