### ISSUE TITLE
Syntax highlighting is not keyword-compliant

### ISSUE THREAD

**Issue by ashipunov** [TeXworks/texworks#776]
_Steps to reproduce the problem_:

1. Enter \sunsection{} (mistype of \subsection{})
2. Check how it is highlighted

_Expected output_:
Should be either not highlighted, or highlighted differently from \subsection{}

_Actual output_:
Highlighted the same way as \subsection{}

_TeXworks version_:  any
_TeXworks obtained from_: whatever
_Operating system_:  any

_Please provide any additional information below_:
Many TeX editors (and even non-TeX like GVim or Medit) can do this. TeXwork is unfortunately not.

**Comment by stloeffler** [comment]
This is (currently) intended behavior.
\sunsection is a valid command (you could define it as ```\newcommand{\sunsection}{code goes here}``` or use a package/class that defines it). As TeX is very flexible in this regard, there is no simple way to know which commands are actually valid and which are not. If we were to define keywords  based on the default article class, someone would most likely report an issue that some komascript command or other is not highlighted properly.
That said, you can easily customize the syntax highlighting patterns to only highlight those keywords you want (see the [TeXworks manual](https://github.com/TeXworks/manual)).

**Comment by ashipunov** [comment]
Dear Stefan,

Thank you for the clarification. I understand. Somehow, I missed the
possibility of tuning the syntax highlighting, I thought that it is
impossible. However, please consider the default behavior of other TeX
editors such as GVim, TeXstudio, and Medit.

With best wishes,

Alexey

2017-01-23 4:10 GMT-06:00 Stefan Löffler <notifications@github.com>:

**Comment by ashipunov** [comment]
Dear Stefan,

I noted errors and even crushes of my TeXworks again, and found in Git that
it might be because of another SyncTeX update. So I started to re-compile
my TeXworks today but unfortunately failed with:

===
In file included from /usr/include/qt4/QtCore/qvariant.h:48:0,
                 from /usr/include/qt4/QtCore/qabstractitemmodel.h:45,
                 from /usr/include/qt4/QtCore/QAbstractListModel:1,
                 from /usr/include/poppler/qt4/poppler-optcontent.h:24,
                 from /usr/include/poppler/qt4/poppler-qt4.h:38,
                 from /home/alexey/wrk/temp/texworks-master/modules/QtPDF/
src/backends/PopplerQtBackend.h:26,
                 from /home/alexey/wrk/temp/texworks-master/build/modules/
QtPDF/../../../modules/QtPDF/src/PDFBackend.h:677,
                 from /home/alexey/wrk/temp/texworks-master/build/modules/
QtPDF/moc_PDFBackend.cpp:9,
                 from /home/alexey/wrk/temp/texworks-master/build/modules/
QtPDF/qtpdf_automoc.cpp:2:
/usr/include/qt4/QtCore/qmetatype.h: In instantiation of ‘static int
QMetaTypeId2<T>::qt_metatype_id() [with T = QList<QPolygonF>]’:
/usr/include/qt4/QtCore/qmetatype.h:230:43:   required from ‘int
qMetaTypeId(T*) [with T = QList<QPolygonF>]’
/usr/include/qt4/QtCore/qmetatype.h:243:23:   required from ‘int
qRegisterMetaType(T*) [with T = QList<QPolygonF>]’
/home/alexey/wrk/temp/texworks-master/build/modules/
QtPDF/moc_PDFDocumentView.cpp:429:88:   required from here
/usr/include/qt4/QtCore/qmetatype.h:169:79: error: ‘qt_metatype_id’ is not
a member of ‘QMetaTypeId<QList<QPolygonF> >’
     static inline int qt_metatype_id() { return
QMetaTypeId<T>::qt_metatype_id(); }

^
modules/QtPDF/CMakeFiles/qtpdf.dir/build.make:453: recipe for target
'modules/QtPDF/CMakeFiles/qtpdf.dir/qtpdf_automoc.cpp.o' failed
make[2]: *** [modules/QtPDF/CMakeFiles/qtpdf.dir/qtpdf_automoc.cpp.o] Error
1
CMakeFiles/Makefile2:141: recipe for target
'modules/QtPDF/CMakeFiles/qtpdf.dir/all'
failed
make[1]: *** [modules/QtPDF/CMakeFiles/qtpdf.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
===

Please advice what to do.

With best wishes,

Alexey


2017-01-23 11:03 GMT-06:00 Alexey Shipunov <dactylorhiza@gmail.com>:

**Comment by ashipunov** [comment]
P.S.

Surprisingly, it had compiled on my other computer. I do not understand the
reason because these machines are almost (~ 99%) full copies of each other.
So I would still be grateful for the advice.

Alexey

2018-01-25 13:07 GMT-06:00 Alexey Shipunov <dactylorhiza@gmail.com>:

**Comment by stloeffler** [comment]
Please try a complete reconfigure & recompile. I.e., start with a new, empty build directory (you can move, rename, or delete your old one if you want). In that empty directory, configure using CMake and then build. 
In many cases, some old settings are still stuck somewhere in the build tree and starting from scratch helps. BTW: which version of Qt are you using?

HTH
Stefan

PS: This issue, besides being closed already, deals with syntax highlighting. It has nothing to do with SyncTeX, or with crashing, or with build problems. In the future, please open new issues for new bugs, or post to the mailing list in cases where you'd like assistance rather than to report a bug in the code.

**Comment by ashipunov** [comment]
Hi,

Thank you.

Qt is 5.5.1, standard for Ubuntu 16.04 LTS.

Sorry -- I did not send my previous message from Github, I sent it from
Gmail instead and therefore was not aware of where exactly it went to...

With best wishes,

Alexey

2018-01-30 13:14 GMT-06:00 Stefan Löffler <notifications@github.com>:

**Comment by stloeffler** [comment]
That's weird, because the snippet you posted mentioned ```/usr/include/qt4``` in several places. If Qt4 and Qt5 get mixed up, it's natural that the build fails. Please try rebuilding from scratch (i.e., in an empty directory) as I suggested before.
Also note that since 52a08ac02e9a680f342621db591d89050d7075ce, CMake should report which Qt5 components are found and if there are any missing (in which case Tw would fall back to Qt4).
