### ISSUE TITLE
insert ZWNJ with script and shortcut in texworks 0.6.2 (qt bug)

### ISSUE THREAD

**Issue by hadi-safi-aghdam** [TeXworks/texworks#789]
hello
in new TeXworks, i can not use ZWNJ in Persian (Farsi) language. (and many people of my country and arabic languages , ...)
(this is qt bug)
Can send me script for inserting ZWNJ Character in texworks (with windows shortcut support)?
I do not able to write script.
thanks

_TeXworks version_: 0.6.2
_TeXworks obtained from_: texlive and texworks site
_Operating system_: windows 10 , 7

**Comment by timhoffm** [comment]
This is https://bugreports.qt.io/browse/QTBUG-42074

Will be fixed in Qt 5.6.3 and Qt 5.9.0.

**Comment by stloeffler** [comment]
Should be fixed in Qt by now.
