### ISSUE TITLE
[reproducible] Freeze of most of the system input

### ISSUE THREAD

**Issue by jdbancal** [TeXworks/texworks#793]
_Steps to reproduce the problem_:

1. Open a document with texworks
2. Compile the document (so that a pdf appears in the viewer window)
3. Set the view to 'Fit to Window'
4. Make sure that the proportion of the viewer window is larger than the page, so that there is some grey area on both sides of the page
5. Long click with the left button of the mouse in the gray area of the viewer window (e.g. on the left of the page)
6. Release the click

_Expected output_:
Nothing should happen: clicking on an empty area should be neutral.

_Actual output_:
The mouse pointer remains in the 'closed hand' form, like if we were able to move the viewer window, but this is not the case. Moreover, clicking again anywhere on the screen doesn't allow to release the click : the mouse can still move, but cannot accomplish any task, it has frozen.

Moreover, most of the keyboard is also unresponsive. Thankfully, the ctrl-alt-F1, ctrl-alt-F2, etc combination still work (so I could open another X session from which I am currently writing). ctrl-alt-left and ctrl-alt-right also work somehow, hence allowing to see what is happening on a different workspace, but every other keystroke seems frozen. In particular, I cannot quit texworks with ctrl-q.

_TeXworks version_: Version 0.5 r.1361 (Debian)
_TeXworks obtained from_: Ubuntu repository
_Operating system_: Ubuntu studio 15.10 Wily

_Please provide any additional information below_:
Ubuntu studio relies on XFCE.

**Comment by stloeffler** [comment]
Thanks for reporting. Your TeXworks version seems very out of date - since then, large parts of the PDF previewer have been rewritten. Can you please try with a more recent version (e.g. compiling it from sources - see the wiki here on GitHub; or by using a package from https://launchpad.net/~texworks - which doesn't include the latest versions as support for Wily has been discontinued officially last year).

**Comment by jdbancal** [comment]
Thanks for your answer @stloeffler!

Following your advice I tried to compile texworks from source (following the instructions in https://github.com/TeXworks/texworks/wiki/Building ), however it didn't work. First I had to install libpoppler-qt4-dev instead of libpoppler-qt5-dev. The I was left with an error at the link stage `libpoppler.so: undefined reference to `TIFFDefaultStripSize@LIBTIFF_4.0'` (I have libtiff5-dev installed, but cannot install libtiff4-dev)...

Anyway, then I used the ppa you mention, and the new version is indeed much better, and it does not have this bug :-) Thanks for that!

Also, I appreciate that it is still possible to see the pdf page by page instead of only continuously b^.^d

**Comment by stloeffler** [comment]
Thanks for testing.

The building page does say to install libpoppler-qt4-dev? In any case, the version must match your Qt version. By default, Qt5 is used nowadays if available, but on Ubuntu this can cause some problems with some versions of the Unity desktop.
Anyway, installing the proper poppler -dev package should pull in the correct tiff -dev package as well. It seems that in your case, poppler is built against and expects libtiff4-dev.

**Comment by jdbancal** [comment]
Hi @stloeffler ,

Sorry I have to reopen this issue. Actually, the version I got from the ppa (0.7~201612081622~git~20a3545~wily) still gives me the global system freeze.

The only difference is that it does not happen when I long click on the grey area of the viewer window, but when I long click on the area of the window which stands on the right of the menus ''File", "Edit, "Search", "Format", ... : long left-clicking with the mouse on the area on the right of these menus and trying to move the window results in the window being moved (when releasing the click), but the mouse pointer remains in the 'closed hand' form, like if we were able to move the viewer window (although this is not the case). Moreover, clicking again anywhere on the screen doesn't allow to release the click : the mouse can still move, but cannot accomplish any task, it has frozen.

Best regards

**Comment by stloeffler** [comment]
Long-clicking (as opposed to short-clicking) is not handled in any special way in the Tw source code. So if this issue only occurs when long-clicking, but not when short-clicking, it is likely related to your window manager in some way. Does long-clicking mean something special (e.g., emulating a right-click on a touchpad) on your system?

a959e08 fixes Tw intercepting context menu events (e.g., from right-clicking) when the mouse is not over the preview. Maybe this helps?

**Comment by stloeffler** [comment]
Closed due to inactivity
