### ISSUE TITLE
Build TeXWorks on OSX Sierra (10.12)

### ISSUE THREAD

**Issue by jlaurens** [TeXworks/texworks#794]
qt4 cannot be installed from brew.
Using macports instead does not help.
How do we do ?

**Comment by stloeffler** [comment]
TeXworks should build fine with Qt5. In fact, I would assume that `brew install qt` already installs qt5 by default?
What exactly did you do, and what is the error, anyway?

**Comment by jlaurens** [comment]
I followed the instructions at
https://github.com/TeXworks/texworks/wiki/Building-on-Mac-OS-X-(Homebrew)
When running
cmake ..
the answer is
```
-- Git commit info updated
CMake Error at /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/FindQt4.cmake:1318 (message):
  Found unsuitable Qt version "" from NOTFOUND, this code requires Qt 4.x
Call Stack (most recent call first):
  CMakeLists.txt:274 (FIND_PACKAGE)


-- Configuring incomplete, errors occurred!
See also "/Volumes/Users/Documents/texworks/build/CMakeFiles/CMakeOutput.log".

```

**Comment by jlaurens** [comment]
As you mentioned, brew installs qt5 by default. But cmake does not ship with a FindQt5.cmake and searches for QT4. So we must tell cmake where to find a FindQt5.cmake:
`cmake .. -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt5/5.9.0_1/
`
It terminates on the following error
```
-- Git commit info updated
[...]
  TeXworks will be installed to:
      /Applications

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
POPPLER_QT_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /Volumes/Users/Documents/texworks/modules/QtPDF
[...]
-- Configuring incomplete, errors occurred!
See also "/Volumes/Users/Documents/texworks/build/CMakeFiles/CMakeOutput.log".
```
No MakeFile so far. I then run `cmake ..` and a MakeFile is smoothly created.
Then `make` and `make install`
Unfortunately, TW crashes at launch time...
