### ISSUE TITLE
Show pdf bookmarks

### ISSUE THREAD

**Issue by hpvd** [TeXworks/texworks#796]
When working with complex documents, it would be very handy to see the pdf bookmarks of a document in the viewer. Not Especially standard document writing (in this pahse only when setting up bookmarks)
but when correcting, optimizing and discussing a document..

**Comment by stloeffler** [comment]
Bookmarks are already available from Windows > Show > Table of Contents.
If you refer to highlighting/outlining links, this can be achieved either in LaTeX with the hyperref package, or you can compile TeXworks in debug mode (add -DCMAKE_BUILD_TYPE=Debug to the cmake command) which will also highlight annotations like links.
