### ISSUE TITLE
Updating synctex 2017

### ISSUE THREAD

**Issue by jlaurens** [TeXworks/texworks#799]
Hi

in order to update TW with later synctex, I'd like to become a developper.

**Comment by stloeffler** [comment]
I sent you an invite.
Note that "simple" updates (that don't change the API or file names) are already automated (using updateSyncTeX.sh which I will adapt to your GitHub repo soon). As for larger changes, the preferred way is to fork the main repo and then send pull requests. If you do want to work on the main repo for some reason, I ask you to do so in a separate branch.
