### ISSUE TITLE
pdf viewer 'magnifying glass' bug

### ISSUE THREAD

**Issue by DuckSoft** [TeXworks/texworks#801]
## Steps to reproduce the problem
1. Compile a normal TeX file and get the **pdf viewer** window (on the right-hand side)
![image](https://user-images.githubusercontent.com/7822648/27898483-d2a4dcd0-6258-11e7-83dc-c640d6effe14.png)
2. Focus on the **pdf viewer** window, press the **left mouse button** on the document, when the 'magnifying glass' will appear.
![image](https://user-images.githubusercontent.com/7822648/27898553-150b3240-6259-11e7-972f-cf9c986cff0e.png)
3. **Hold** the left mouse button and meanwhile **click** right mouse button, when a popup menu will appear.
![image](https://user-images.githubusercontent.com/7822648/27898644-6e4b4fac-6259-11e7-81f8-b8b8318031de.png)
4. Perform any one of the actions mentioned in the following section will trigger the bug.
5. Bug occurs! Move your mouse pointer around the document, and the 'magnifying glass' will **stick to your mouse pointer**, even if you pressed the left mouse button again, trying to close it!

## Known bug triggers
For step 4 of last section:
 - Click 'Esc' button to escape from the popup menu
 - Select any menu item to perform in the popup menu
 - Move your mouse pointer out of the *menu area*, but **within** the *magnifying area*, and then click. Followed is a picture illustrating the concept of 'menu area' and 'magnifying area'. 
![image](https://user-images.githubusercontent.com/7822648/27898807-278b3cde-625a-11e7-81a6-62923cfef458.png)
 - ...And more? That's all I've known. 

## Known bug eliminators
When bug occurs, perform one of the following actions will eliminate the bug:
 - Click right mouse button again to call the popup menu, and then make a left mouse click **outside the menu area and the magnifying area**
    (For area reference, visit last section)
 - Click "Win" button on the keyboard twice, when the residue of the magnifying glass will stain the document:
![image](https://user-images.githubusercontent.com/7822648/27899298-384825a8-625c-11e7-9139-e61724f6e0f8.png)
  Then make a click **outside** the residue area. (When your mouse icon turned a blue magnifying glass icon with a "-" on it, it indicates that you have escaped the residue area. ) The magnifying glass will then move quickly to your mouse pointer and in a flash it disappears. 
 - ...And more? That's all I've known. 

## Other bug information
_TeXworks version_: Now using 0.6.2 (but I've tried all versions with a pdf viewer, bug occurs. )
_TeXworks obtained from_: GitHub release
_Operating system_: Tested on Windows 7 (and some older versions on Windows XP)

**Comment by stloeffler** [comment]
Thanks for the very detailed bug report - that helped a lot. Should be fixed in 7726d35

**Comment by DuckSoft** [comment]
My pleasure.
