### ISSUE TITLE
Fine pdf to tex synchronisation fails near the paragraph left boundary.

### ISSUE THREAD

**Issue by jlaurens** [TeXworks/texworks#803]
Typeset the following document with pdf latex in A4
```
\documentclass{minimal}
\begin{document}
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
\end{document}
```
The fourth line in the pdf output reads
```nulla pariatur. Excepteur...```

Fine synchronization from pdf to source works for all the letters, except the first ones n, u and l.

**Comment by stloeffler** [comment]
This works for me with the current 1.18 version of the SyncTeX parser. 
It does fail for 1.19, though, as in those cases synctex_edit_query() incorrectly returns line 4 (thus causing text-based fine sync to fail). Maybe this is related to jlaurens/synctex#5?

**Comment by jlaurens** [comment]
This is not connected to  jlaurens/synctex#5? and this is not really incorrect by TeX rules. The synctex file reads
```
x1,3:35522149,6964510
k1,3:35522149,6964510:0
)
(1,4:4736286,7750942:30785863,455111,127431
x1,4:5100376,7750942
x1,3:6138032,7750942
k1,3:6314642,7750942:176610
```
The fourth and fifth lines above (1 based) indicate that the box and the x node were created while parsing the 4th line, but all the surrounding nodes where created while parsing line 3. When the hit spot is closer to the synctex node at line 5 (clicking on letters 'n', 'u', 'l'), the returned line number is 4, but when it is closer to the synctex node at line 6, the returned line number is 3.

I did not find yet a proper algorithm to deal with such situations in general. I'll see what I can do to help and post something when it is ready. In the meanwhile, there is a poor man solution: if fine synchronisation fails with some line, try with the preceding one...

Stay in touch.
