### ISSUE TITLE
Feature/Script for opening PDF-file with other than system default pdf viewer

### ISSUE THREAD

**Issue by hpvd** [TeXworks/texworks#805]
When doing some "advanced" things within a pdf, one sometimes need to look how this works within the most common used PDF viewer: acrobat reader.

But this viewer, may not always be the one you really use on daily base, because in most cases you prefer a much faster one like sumatra view (which is your default viewer)

So the problem is:
You actually have no possibility to open the pdf file from within texworks pdf viewer within another non default pdf viewer.
=> Would be awesome to have a possibility to simply put in the path to the viewer you would like to use.

**Comment by stloeffler** [comment]
Actually, it's pretty easy to modify the [launchPdf.js](https://github.com/TeXworks/texworks/blob/master/res/resfiles/scripts/launchPdf.js) script bundled with TeXworks. Simply replacing
```
retVal = TW.launchFile(TW.target.fileName);
```
by
```
retVal = TW.system("c:\\path\\to\\app.exe \"" + TW.target.fileName + "\"");
```
should do the trick. Note the escaping of the `\` and `"` characters in the command line by prefixing them with `\`. This should take care of basic needs, but of course may need adapting if, e.g., your filename contains special characters or your pdf program needs special parameters etc.

Note: You should also make sure to update the script's metadata, like title, description, etc.
