### ISSUE TITLE
Show summary of file size, number of pages and document name

### ISSUE THREAD

**Issue by hpvd** [TeXworks/texworks#806]
It's only a tiny thing, but during optimization of the PDF, it would be very handy to have a direct summary of information about
 - file size,
- number of pages,
- document name

Maybe a good place for this would be the "meta date box."

All other needed data like fonts, meta data, permissions are already there :-)

_TeXworks version_: 0.62
_TeXworks obtained from_: Miktex
_Operating system_: W10

**Comment by ousia** [comment]
I think it is important to show full metadata info from PDF document:

* Title
* Author
* Subject
* Keywords
* Creator
* Producer
* CreationDate
* ModDate

**Comment by stloeffler** [comment]
@hpvd: I added file size to the meta data. The file name is shown in the window's title bar, the number of pages is shown in the status bar (bottom right).

@ousia: The PDF meta data is already shown in the meta data info widget (available from Window > Show > Meta Data).

I also added the page size to the meta data.

**Comment by ousia** [comment]
@stloeffler, many thanks for the reply.

After having tested it, how about a shortcut (at least for metadata) such as `ctrl+d`? (As far as I remember, this is the shortcut in _Adobe Acrobat_.)
