### ISSUE TITLE
GUI lags on huge files

### ISSUE THREAD

**Issue by basti98** [TeXworks/texworks#810]
_Steps to reproduce the problem_:

When using newest TeXworks (0.6.2) on huge files (> 10MB Text, > 2000 pages) the UI becomes extremely laggy and freezes regularly for several seconds.
This happens will different macro sets and input data so I assume this problem is based on size only.

My parallel older version (0.4.4) doesn't show this issue with identical data on same PC.

_TeXworks version_: 0.4.4 / 0.6.2
_TeXworks obtained from_:  MikTeX distribution / TeXworks website
_Operating system_: Win 7-64

**Comment by stloeffler** [comment]
By UI, do you mean the PDF previewer UI or the TeX editor UI (or both)? Could you please test each case separately (e.g., copy the tex file to a temporary folder and open it in TeXworks to avoid opening the pdf as well; then do the same with just the pdf file)

Do you have a single huge TeX file, or is the document split across several files?

Does this still happen when you set Edit > Preferences... > Editor > Syntax coloring = None, Edit > Preferences... > Editor > Spell-check Language = None, Scripts > Scripting TeXworks > Manage Scripts > Hook Scripts: uncheck all scripts. Then close TeXworks, copy the files to a new location, an then open them with TeXworks (the new location is important as TeXworks remembers some settings such as syntax highlighting for files)

Does this happen only when editing text (typing, deleting, etc.) or also when you just scroll around?

**Comment by basti98** [comment]
Stefan,

sorry for delay in answering your questions concerning my bug report but 
I had a tight schedule the last weeks.

Here the results of your requested tests.

Both parts are laggy: editor and viewer as long as editor is opened. 
Editor alone is slow, viewer alone works as expected.

I have a single huge file (10MB, ~140k lines of text).

The requested changes in Preferences and Scripts or the different 
locations make no difference in behaviour of the editor.

Ever user interaction is affected as the Texworks.exe process consumes 
permanently one CPU core.

During the tests I further noticed some things you may be interested in:

When starting Miktex.Texworks.exe (0.4.4) the editor uses around 25 
seconds cpu-time (100% one core). After startup usage of cpu if this 
process drops to 0 and stays low while formatting or browsing in viewer.

In Texworks.exe (0.6.2) editor permanently consumes 100% of one cpu 
core, I cancelled this after ~ 30minutes.

Highlighting in 0.6.2 only affects beginning of huge file.

Typesetting in 0.6.2 fails to work correctly for the complete document. 
I get TeX errors and wrong special characters (crossed box in viewer) 
which don't appear when doing Ctrl-T in 0.4.4 TeXworks. - Both editors 
are of course linked to same MikTeX installation.

PS: Could please confirm receive of this email? I don't know if I could 
trust GitHub email reply...



Kind regards,
Sebastian Weyrauch

______________________________
Sebastian Weyrauch
bsix information exchange GmbH
Sophienstraße 40
38118 Braunschweig
Germany
Fon +49 (0) 531 681328
Fax +49 (0) 531 681330
s.weyrauch@bsix.de
Registergericht:
Amtsgericht Braunschweig HRB 5115
Geschäftsführer:
Frank Beyerlein, Sebastian Weyrauch
______________________________



------ Originalnachricht ------
Von: "Stefan Löffler" <notifications@github.com>
An: "TeXworks/texworks" <texworks@noreply.github.com>
Cc: "basti98" <s.weyrauch@bsix.de>; "Author" <author@noreply.github.com>
Gesendet: 10.08.2017 13:11:31
Betreff: Re: [TeXworks/texworks] GUI lags on huge files (#810)

**Comment by basti98** [comment]
Joseph,

yeah its somewhat bigger ;) but earlier version 0.4.4 handles it 
gracefully...

**Comment by stloeffler** [comment]
I just fixed a bug in the syntax highlighter. Hopefully this will give you a more responsive GUI.
As far as typesetting is concerned, I think nothing has changed between 0.4.4 and 0.6.2 code-wise, so if you run the same version of the same engine I don't see any reason why the results should differ (there are differences between, e.g., luatex and pdftex, of course, though). However, typesetting should not really be affected by file size, so if you could come up with a minimal (small) example I could test further.
