### ISSUE TITLE
Update regex system to use Qt5 QRegularExpression

### ISSUE THREAD

**Issue by josephwright** [TeXworks/texworks#819]
TeXworks is now built with Qt5, which in http://doc.qt.io/qt-5/whatsnew50.html is documented as having a more powerful regex system than in the past. In particular, using this would enable more complex syntax highlighting (see _e.g._ https://github.com/TeXworks/texworks/issues/778).

**Comment by stloeffler** [comment]
Fixed in a9626265bad0610a937412f95ea1ccee8273e104
