### ISSUE TITLE
TeXworks 0.6.2 and 0.7 are not compatible with TeXLive 2017

### ISSUE THREAD

**Issue by ashipunov** [TeXworks/texworks#823]
_Steps to reproduce the problem_:

1. Download project files from http://ashipunov.info/shipunov/school/biol_448/nd_manual/ (including subdirectories contents)
2. Run TeXworks 5-7 times

_Expected output_: no crashes

_Actual output_: random crashes

_TeXworks version_: Version 0.7 (personal) [r.7bb2dfd, 4/23/17 3:18 PM] AND Version 0.4.5 r.1280 (personal)
_TeXworks obtained from_:  Github
_Operating system_:  Linux 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

_Please provide any additional information below_: Might be related with includes and synctex but I am not sure

**Comment by ashipunov** [comment]
After thorough research of the problem, I found that **TeXworks**  (I checked 4 versions) **is incompatible with TeXLive 2017**! Everything works without crashes on TeXLive 2016 but on TeXLive 2017, even on completely fresh install, crashes are regular. Crashes appear not only on my project mentioned above but also on my older projects which worked perfectly last year. Typically, you cannot run the project more then three times without crash. On TeXLive 2016, however, one can run them without crashes for the very long time. Actually, I never saw any crash yet.
My solution so far is to use TeXLive 2016 (fortunately, I had a full backup). However, this is not good. Please help.

**Comment by ashipunov** [comment]
I do not know how to rename the topic so I will open another one with the link to this one. Please rename this one.

**Comment by ashipunov** [comment]
Update. Now I think that this is likely SyncTeX. When using TeXLive 2017, there are two kinds of outcome:

1) SyncTeX ERROR: Bad math record (2).
SyncTeX ERROR: Bad sheet content.
SyncTeX ERROR: SyncTeX Error: Bad content

and then "Jump to PDF" does not work, and "Jump to source" does not appear at all.

OR

2) no messages, jumps work for some time but then program crashes.

Same things happen if one simply replace "synctex" executable from TL 2017 with "synctex" from TL 2016.

Both these effects absent in TeXLive 2016.

**Comment by stloeffler** [comment]
Thanks for investigating and finding out about SyncTeX. SyncTeX apparently was updated fairly recently in TeXLive. I now updated SyncTeX in TeXworks as well, so hopefully using matching versions helps.

However, if the problem occurs with the synctex command line utility as well, you should probably report this issue to [jlaurens/synctex](https://github.com/jlaurens/synctex) and/or to the TL developers.

**Comment by ashipunov** [comment]
Thank you. Now everything works with TeXLive 2017 and newest TeXworks without crashes!
Some of my projects output multiple

```
Negative width
Negative width
Negative width
Negative width
Negative width
```

but without any visible consequences; forward and reverse searches work fine.

**Comment by stloeffler** [comment]
Excellent. Thanks for testing.
