### ISSUE TITLE
Unclear documentation about spellchecking dictionaries on Linux

### ISSUE THREAD

**Issue by alexeymuranov** [TeXworks/texworks#827]
_TeXworks version_: 0.6.1
_TeXworks obtained from_: Ubuntu repository 
_Operating system_: Ubuntu 17.04

_Please provide any additional information below_:

I cannot figure out where TeXWorks actually looks for spellchecking dictionaries and do not understand why without any special setup i have a few dictionaries on my Ubuntu system, but on another Linux Mint system there are no dictionaries in TeXWorks menu.

According to the documentation i've seen (not very clear), TeXWorks can either use system's Hunspell dictionaries (should installing them with `apt` be sufficient? i suppose not...), or look for dictionaries in `/usr/share/myspell/dicts`, or in `~/.TeXworks/dictionaries`. However this does not seem to be what TeXWorks is doing.

Here is what i have in `/usr/share/myspell/dicts`:
```
$ ls /usr/share/myspell/dicts
fr_BE.aff  fr_CA.aff  fr_CH.aff  fr_FR.aff  fr_LU.aff  fr_MC.aff
fr_BE.dic  fr_CA.dic  fr_CH.dic  fr_FR.dic  fr_LU.dic  fr_MC.dic
```
Here are the Hunspell dictionaries installed on my system:
```
$ apt list --installed "hunspell-*"
Listing... Done
hunspell-en-au/zesty,zesty,now 1:5.2.5-1 all [installed]
hunspell-en-ca/zesty,zesty,now 1:5.2.5-1 all [installed]
hunspell-en-gb/zesty,zesty,now 1:5.2.5-1 all [installed]
hunspell-en-us/zesty,zesty,now 20070829-6ubuntu3 all [installed,automatic]
hunspell-en-za/zesty,zesty,now 1:5.2.5-1 all [installed]
hunspell-fr/zesty,zesty,now 1:5.7-1 all [installed]
hunspell-fr-classical/zesty,zesty,now 1:5.7-1 all [installed,automatic]
hunspell-ru/zesty,zesty,now 1:5.2.5-1 all [installed]
```
I do not have `~/.TeXworks/dictionaries` folder.

However, the list of dictionaries available in TeXWorks does not include neither all Hunspell dictionaries, nor the contents of `/usr/share/myspell/dicts`: i have there `en_AU`, `en_CA`, `en_ZA`, `en_GB`, `en_US`, `fr_MC`, `ru_RU`.

On another Linux Mint system, there are a few Hunspell dictionaries installed and there are some dictionaries in `/usr/share/myspell/dicts`, but nothing shows up in TeXWorks.

**Comment by stloeffler** [comment]
Tw should, by default, look in `/usr/share/myspell/dicts` and `~/.TeXworks/dictionaries`. The former is configurable using the environment variable `TW_DICPATH`.
Up until rev. 4cb6650, when Tw found multiple dictionaries sym-linked to the same file, it showed only one of those dictionaries in the menu. This might be what happened to you - you could try `ls -lisa /usr/share/myspell/dicts` to see such symlinks. Starting with rev. 4cb6650, Tw now shows all dictionaries.

For dictionaries to show up, both .aff and .dic files must be present. Also, on my system, dictionaries installed to `/usr/share/hunspell` and had to be symlinked to `/usr/share/myspell/dicts` manually.
