### ISSUE TITLE
Crash when opening certain bib files.

### ISSUE THREAD

**Issue by fbrewster** [TeXworks/texworks#829]
_Steps to reproduce the problem_:

1. Open bib file
2. Copy contents
3. Close bib file

_Expected output_:
Copy and paste into other bib file

_Actual output_:
TeXworks goes unresponsive

_TeXworks version_:  0.6.1
_TeXworks obtained from_: MikTeX 2.9.6210
_Operating system_: Windows 64bit

_Please provide any additional information below_:
[Bib file used](https://github.com/TeXworks/texworks/files/1481985/bib.file.zip)

**Comment by stloeffler** [comment]
I tried with the latest version of TeXworks (and with copying the contents of your bib file into an empty other file), but could not reproduce the crash.
Could you:
 1) try with the latest version from https://bintray.com/texworks/Windows-latest/TeXworks-for-Windows%3Alatest#files
 2) check if this is related to whether syntax highlighting and/or spell checking are turned on or off
 3) check if this depends on the file you copy to
 4) check if it is relevant which application you copy from (I assume you copied from TeXworks to TeXworks - but does this also happen if you copy, e.g., from notepad to TeXworks?)

**Comment by stloeffler** [comment]
Closed due to inactivity and because it was reported against an outdated version of Tw.
