### ISSUE TITLE
Layout problem when using dictionaries

### ISSUE THREAD

**Issue by rickhev1** [TeXworks/texworks#831]
_Steps to reproduce the problem_:

1.  Use dictionaries, perhaps from Miktex.  set spelling preferences to English-US.
2.  Change the attached file type from txt to tex.
3.  Open the file.

_Expected output_: successful open

_Actual output_:
'Layout Problem. A problem occured (sic) while laying out the loaded document in the editor. This is caused by an issue in the underlying Qt framework and can cause TeXworks to crash under certain circumstances. The symptoms of this problem are hidden or overlapping lines. To work around this, please try one of the following: -) Turn syntax highlighting off and on -) Turn line numbers off and on -) Resize the windows We are sorry for the inconvenience.'

_TeXworks version_: 0.6.2 (MiKTeX 2.9.6520 64 bit)
_TeXworks obtained from_: Miktex
_Operating system_: Windows 10 1709 update

_Please provide any additional information below_:
No error if you have spelling pref. set to None.  I also downloaded texworks git_862d10  from bintray and tested with that.  It exhibits the same symptoms.  No error until I set up dictionaries and set spelling pref. to Engish-US.  Then I get the Layout problem.  I get the error only with the tex file I am attaching, not with others, all of which are smaller.
[a spiv.txt](https://github.com/TeXworks/texworks/files/1586151/a.spiv.txt)

**Comment by rickhev1** [comment]
Just retested using git_395cae5, dated 20180307.  Same problem.

**Comment by AlainAtom** [comment]
On my side I have the layout error message while opening a TeX file of 24ko, even with spelling preferences set to none. The file always produce the error message when I open it. I don't have any other problem than the message. I don't have the message with smaller files.

**Comment by rickhev1** [comment]
Interesting.  I get the error when I use Miktex on a file of 77 kb even with spell check none.  When I use Miktex on a file of size 32 kb, I get no error even with spell check on.  When I use  a later Texworks downloaded from bintray, on the 77 kb file I get no error with spell check none, but  I get the error with spell check on.

**Comment by stloeffler** [comment]
The "slow syntax highlighting" issue has been fixed. The "disappearing lines" message box (#469) is an error of the underlying Qt framework, not a Tw one. It has has recently been fixed in the development version of Qt and will be implemented in Tw as soon as the respective Qt release versions become available
