### ISSUE TITLE
Add .nav and .snm to the list of auxiliary files extensions

### ISSUE THREAD

**Issue by jlaurens** [TeXworks/texworks#835]
These are file extensions used by beamer, at least the first one for sure.
.nav aux files need to be deleted when a different version of beamer is used to typeset the document.
Thanks

**Comment by nignasi** [comment]
This one is easy to solve. You can edit `texworks-config.txt` file where you will find some lines starting with `cleanup-patterns`. You can add new one with missing `beamer` auxiliary files. I've added one which contains: 

`cleanup-patterns:	$jobname.nav $jobname.snm $jobname.synctex.gz $jobname.vrb`

**Comment by stloeffler** [comment]
I added patterns for .nav and .snm as requested. Note that this only takes effect when you haven't modified `texworks-config.txt` yourself.

Also note that .synctex.gz is not (really) an auxiliary file but rather an output file (similar to .pdf), and therefore should generally not be deleted by default (hence it's not in the list)
