### ISSUE TITLE
Add new required default pdflatex path

### ISSUE THREAD

**Issue by davelab6** [TeXworks/texworks#836]
_Steps to reproduce the problem_:

1. Use a macos computer
2. Install mactex and texworks
3. Try to compile a document using pdflatex

_Expected output_:

Document compiles

_Actual output_:

Path error

_TeXworks version_: 
_TeXworks obtained from_: 
_Operating system_: 

_Please provide any additional information below_:

Required path is

    /usr/local/texlive/2017/bin/x86_64-darwin

Please add this to the default list (found in Preferences -> Typesetting -> Paths for Tex and related programs)

**Comment by davelab6** [comment]
MacTeX 2017 from tug

TeXworks version 0.6.2. 

Operating system: macOS High Sierra Version 10.13.2

**Comment by stloeffler** [comment]
This path should be present by default (if it exists in the file system). _However_, when TeXworks is run (more specifically: when the preferences are saved), the current paths are saved and override the defaults. Hence, if you upgraded an old system (on which the mentioned path did not exist originally), only the old paths will have been saved previously and therefore show up now.

It should be possible to use the "Restore Defaults" button in the preferences dialog to recover the default paths - be aware, though, that this will also restore defaults for other things, such as the processing tools. Alternatively, you can add the path manually, of course.

**Comment by davelab6** [comment]
Thanks for explaining; this was very confusing for a friend; perhaps if
'pdflatex' could not be found on the current paths, TeXWorks could check
the defaults and if it is found there, ask the user if they want to add
that path to make it work?
