### ISSUE TITLE
Red lines by spell checker

### ISSUE THREAD

**Issue by pseudoniem** [TeXworks/texworks#837]
_Steps to reproduce the problem_: Came across [this question](https://tex.stackexchange.com/q/424312) on TeX.SE. Thought it would be good to mention it here. Tried it on my computer and experienced the same problem.

_Expected output_: A red line under wrongly spelled words

_Actual output_: No red line under wrongly spelled words

_TeXworks version_: 0.6.2
_TeXworks obtained from_: Miktex
_Operating system_: Windows10

_Please provide any additional information below_: Spell check does appear to be active, since you can get suggestions of correctly spelled words. Only the visual indication seems to be missing.

**Comment by stloeffler** [comment]
716cd01 works around/fixes a bug with the spell checking underline. However, the original post on stackexchange mentions a customized syntax highlighting file, which is abusing syntax highlighting for coloring text. As a side effect, the specific syntax highlighting customization mentioned treats each single character as a keyword that is to be highlighted (and spell-checked) separately. As single characters are rarely words that actually _can_ be spellchecked, this effectively renders spellchecking mostly useless.

The correct way for changing the default text color would be to use [Qt stylesheets](http://doc.qt.io/qt-5/stylesheet-syntax.html). E.g., create a file `style.css` containing
```
QTextEdit { color: #cccccc; }
```
And then run TeXworks using `TeXworks.exe -stylesheet style.css`. This should turn all text in all text edit fields very light gray (add a `background-color: ...` statement to also set the background color).
