### ISSUE TITLE
TeXWorks window larger than desktop

### ISSUE THREAD

**Issue by maesumi** [TeXworks/texworks#838]
_Steps to reproduce the problem_:

1. Run TexWorks 
2. Try to close the window.
3. 

_Expected output_: a normal TeXWorks window.

_Actual output_: Task bar and the icons for closing, or minimizing disappear

_TeXworks version_: 2.12.8  
_TeXworks obtained from_: github
_Operating system_: Win10 64 bit

_Please provide any additional information below_:
When I open TeXWorks the resulting window appears larger than my monitor desktop. It takes over the task bar; and the icons for closing the screen or minimizing do not appear either. My only option is to use Control-Alt-Delete to stop the program.  The older version did the same thing. Problem has appeared recently. Could be a connected to a Win10 Creator upgrade.

**Comment by stloeffler** [comment]
I didn't see this so far (but I could not check with the recent Creator update). However, 2a5ae3e fixes a screen placement bug, maybe that is related.
