### ISSUE TITLE
libpoppler-qt4-4 still required dependency on development ppa ubuntu bionic

### ISSUE THREAD

**Issue by charlesnix** [TeXworks/texworks#840]
_Steps to reproduce the problem_:

1. add development ppa to sources.list
2. apt update
3. apt install texworks

_Expected output_: normal  installation

_Actual output_: dependency for libpoppler-qt4-4 cannot be satisfied

_TeXworks version_: 0.7~201803282001
_TeXworks obtained from_: development ppa
_Operating system_: ubuntu bionic

_Please provide any additional information below_:
For the stable branch 0.6.2-2   dependency is libpoppler-qt5-1.  However stable has not been very stable in daily operation for me compared with development.  libpoppler-qt4 is phased out beginning with bionic.  stable ppa already has dependencies changed.

**Comment by texervn** [comment]
You can build Poppler from source using 0.61 (https://poppler.freedesktop.org/poppler-0.61.1.tar.xz).
