### ISSUE TITLE
Delay in syntax highlighting

### ISSUE THREAD

**Issue by klelandw** [TeXworks/texworks#843]
_Steps to reproduce the problem_:

1.  Start new comment (%)
2.  Type comment

_Expected output_:

Text should be red (default color scheme)

_Actual output_:

Tex is black, turns red after ~0.1s.

_TeXworks version_: 2018-05-12
_TeXworks obtained from_: bintray
_Operating system_: Windows

_Please provide any additional information below_:

This is just annoying, not a critical issue.

**Comment by stloeffler** [comment]
Does this still occur with the latest version of Tw? IIRC, there have been some optimizations in the syntax highlighting code.

**Comment by stloeffler** [comment]
Closed due to inactivity and because it was reported against an outdated version of Tw.
