### ISSUE TITLE
Texwork crashes at the end and 1 of 6 CPUs run at 100%

### ISSUE THREAD

**Issue by tczillay** [TeXworks/texworks#857]
_Steps to reproduce the problem_:

1. tried to compile a file with texworks, output (LuaLaTeX)
2. It ran through the ~460 Pages like the last months
3. it writes the fpdf-file and than crashes into vain

_Expected output_:

_Actual output_:

_TeXworks version_: 
_TeXworks obtained from_: 
_Operating system_: 
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
Desktop: Mate
RAM: 16GB
_Please provide any additional information below_:
this is what terminal gave me when I ran it from terminal:
`
earl@earl:~$ texworks 
pdfTeX 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian)
kpathsea version 6.2.3
Copyright 2017 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.34; using libpng 1.6.34
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with poppler version 0.62.0
Speicherzugriffsfehler (Speicherabzug geschrieben)
earl@earl:~$ 
`
this ist kern.log
`
Mar 19 18:00:36 earl kernel: [  844.087697] texworks[6053]: segfault at 56345f6d1e60 ip 000056345f6d1e60 sp 00007ffe828ef918 error 15`
this ist syslog:
`Mar 19 18:00:36 earl kernel: [  844.087697] texworks[6053]: segfault at 56345f6d1e60 ip 000056345f6d1e60 sp 00007ffe828ef918 error 15`
I tried reinstall texlive but this failed too.
The temperature is low, about 28°C,

**Comment by tczillay** [comment]
Well, I tried it with an other PC, it is still the same. Now I use the terminal to compile. This works but it's not comfortable. Looked to find an error in the text I use, tried to delete sentence for sentence, sometimes it works with a sentence, the next time it crashes.
I tried the workarounds in issue 847. Don't help.

**Comment by stloeffler** [comment]
This sounds a lot like #810 which has been fixed in the recently released 0.6.3 version.
What version of TeXworks are you using?

**Comment by tczillay** [comment]
Maybe. The files are not so big. there is no .deb-Package arround?
(meanwhile I tried to run texworks from texlive installation for Win, was the same, told me \bin\win32\runscript.tlu:902:command failed with exit code -1073741819:texworks)
I try to get 0.0.3 thx

**Comment by tczillay** [comment]
Everything works fine now! Installed newest version.
Thanx for help!!

**Comment by tczillay** [comment]
Could be closed.
