### ISSUE TITLE
Problem with pdf rendering in TeXworks

### ISSUE THREAD

**Issue by nignasi** [TeXworks/texworks#860]
I'm using last TeXworks version on Windows 10 on a new laptop with 1920x1080 resolution display. I've been using TeXworks for years although in other computers.

On this laptop all figures are shown with a very low definition. As an example I attach two fragments of a display capture. One shows the rendering on texworks previewer and the second on sumatrapdf, as you can see second figure shows nice while first one not. 

I suppose I'm doing something wrong but I don't know what. Could you help me?

Thank you.

![Texworksview](https://user-images.githubusercontent.com/2562430/57149094-5007fc00-6dcb-11e9-8a38-4db525ebca46.PNG)
![Sumatraview](https://user-images.githubusercontent.com/2562430/57149129-59916400-6dcb-11e9-95e8-9ccf5aa89d8e.PNG)

**Comment by stloeffler** [comment]
Can you provide the pdf for testing?

**Comment by stloeffler** [comment]
Did this improve with the recent addition of high-dpi display support?

**Comment by stloeffler** [comment]
Closed due to inactivity
