### ISSUE TITLE
Not finding Pygmentize

### ISSUE THREAD

**Issue by skubesch** [TeXworks/texworks#863]
_Steps to reproduce the problem_:

1. Using Minted package with TeX

_Expected output_:
PDF file generation 

_Actual output_:
(/usr/local/texlive/2019/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg)))system returned with code 256

! Package minted Error: You must have `pygmentize' installed to use this packag
e.

_TeXworks version_: 0.6.3
_TeXworks obtained from_: tug.org
_Operating system_: Mac OSX 10.14.4

_Please provide any additional information below_:

This issue is not present with TeXWorks 0.6.2. Pygmentize was installed using `sudo easy_install Pygments`. Files generate successfully when moving back to the previous version of TeXWorks (0.6.2) so it does not seem to be related to the installation of python's pygmentize, but possibly an issue with finding it?

**Comment by stloeffler** [comment]
It seems that this is related to #861 which, from what I can tell so far, seems to be related either to how Mac OS X handles environment variables or to how Qt processes them.
In any case, #861 mentions a few workaround that might help you.
