### ISSUE TITLE
More precise window title bar on OS X

### ISSUE THREAD

**Issue by jlaurens** [TeXworks/texworks#872]
I you open both `.../foo/file.tex` and `.../bar/file.tex` at the same time, you end up with two windows with the same title bar reading "file.tex - TeXworks", which one corresponds to which file ? There are also 2 entries in the window menu with the same title reading "file.tex", same ambiguity here...

Suggestion : add some info in the window title to make the difference, something like
"file.tex [foo] - TeXworks" and "file.tex [bar] - TeXworks", which contains the last component that differs between both file paths.

Also, the window menu entries could respectively ead "file.tex [foo]" and "file.tex [bar]"

This kind of ambiguity also appears in the menu to open recent documents.

Of course the problem could occur with more than 2 files and may also occur on other OS's.

**Comment by stloeffler** [comment]
Which version are you using? Did you try with the the development version where this was (supposedly) fixed a while back (see #853)?

**Comment by jlaurens** [comment]
Hi Stefan

I thought I was using the latest version, but I was not!
I add to remove some old versions of texworks in order to have the proper .tex → latest texworks binding.

Sorry for the disturbance, I should have fixed the problem by myself

Thanks

JL

----- Mail original -----
De: "Stefan Löffler" <notifications@github.com>
À: "TeXworks/texworks" <texworks@noreply.github.com>
Cc: "Jérome LAURENS" <jerome.laurens@u-bourgogne.fr>, "Author" <author@noreply.github.com>
Envoyé: Samedi 19 Octobre 2019 12:20:44
Objet: Re: [TeXworks/texworks] More precise window title bar on OS X (#872)

Which version are you using? Did you try with the the development version where this was (supposedly) fixed a while back (see #853)?
