### ISSUE TITLE
Prevent typesetting concurrency with master/slave input files

### ISSUE THREAD

**Issue by jlaurens** [TeXworks/texworks#874]
_Steps to reproduce the problem_:

1. given master.tex
2. given slave.tex that declares % !TEX root = main.tex

Actually, it is possible to typeset both slave.tex and master.tex at the same time, which results in two identical typesetting command running concurrently leading to undetermined results with respect to aux and output files, at least.

**Comment by stloeffler** [comment]
Fixed in c99fb13
