### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by jakobjakobson13** [TeXworks/texworks#877]
Dear developers,

could you provide flatpak support? This could be an interesting packaging option for the future and you could probably just adapt the (already working) flatpak manifest from [texstudio](https://github.com/flathub/org.texstudio.TeXstudio).

Regards

Jakob

**Comment by stloeffler** [comment]
See flathub/flathub#1283

**Comment by stloeffler** [comment]
https://flathub.org/apps/details/org.tug.texworks

**Comment by jakobjakobson13** [comment]
Thank you very much for closing this bug report so quickly.
