### ISSUE TITLE
OSX: No quit menu item

### ISSUE THREAD

**Issue by jlaurens** [TeXworks/texworks#878]
**Bug description:**

No quit menu under the TeXworks menu on OS X when no document is open, I have to force quit or open a document.

**Steps to reproduce the problem:**

1. Open TeXworks
2. Close the 'untitled' window

**Expected behavior:**

Have the quit menu item at the bottom of the TeXworks menu

**General information:**
_TeXworks version_: 0.6.3
_TeXworks obtained from_: Sourceforge
_Operating system_: OSX 10.13.6

**Additional information:**

**Comment by stloeffler** [comment]
I am not very familiar with how OS X handles (global) menus. The relevant code is in [src/TWapp.cpp](https://github.com/TeXworks/texworks/blob/master/src/TWApp.cpp#L181-L231). There, a global menu bar is created (as per the [Qt docs](https://doc.qt.io/qt-5/qmenubar.html#qmenubar-as-a-global-menu-bar)) and several menus and items are added. In particular, the "Quit TeXworks" item is added to the "File" menu. Note, though, that according to the Qt docs, this should likely be moved to the application menu (and even if that fails, a default "Quit" item should be created).

So, how does the menu bar look like if there is no open document? Is there a "File" (and a "Help") menu? If so, which menu items are available in there?
Also, what menu items are in the application menu? In particular, is there an "About TeXworks" menu item anywhere (this should be handled in a similar way as the "Quit" item)?

Ideally, could you provide some screenshots?

**Comment by jlaurens** [comment]
Starting main menu:
![Capture d’écran 2019-12-05 à 13 29 47](https://user-images.githubusercontent.com/1617871/70235517-63b18180-1763-11ea-94da-fbd46fb615bc.png)
Main menu after closing the untitled document
![Capture d’écran 2019-12-05 à 13 27 30](https://user-images.githubusercontent.com/1617871/70235537-6dd38000-1763-11ea-8444-8942756a7be8.png)
Main menu after opening a non void document
![Capture d’écran 2019-12-05 à 13 25 11](https://user-images.githubusercontent.com/1617871/70235546-7330ca80-1763-11ea-8895-bb6f8eee96c4.png)
Main menu after closing that document
![Capture d’écran 2019-12-05 à 13 28 00](https://user-images.githubusercontent.com/1617871/70235558-788e1500-1763-11ea-92bd-26f247f162a8.png)
Last situation: open a non void document in TW then open a void document, no edit submenu...
![Capture d’écran 2019-12-05 à 13 35 32](https://user-images.githubusercontent.com/1617871/70236086-84c6a200-1764-11ea-8690-c72392183a5e.png)

**Comment by jlaurens** [comment]
Main menu at start
![Capture d’écran 2019-12-05 à 13 27 30](https://user-images.githubusercontent.com/1617871/70236624-93fa1f80-1765-11ea-9b5a-713af6c34570.png)
When closing the untitled document
![Capture d’écran 2019-12-05 à 13 29 47](https://user-images.githubusercontent.com/1617871/70236256-e129c180-1764-11ea-9c24-cc8d21c543c2.png)
After opening a non void document
![Capture d’écran 2019-12-05 à 13 25 11](https://user-images.githubusercontent.com/1617871/70236689-b8ee9280-1765-11ea-9786-d35fb3cb6873.png)
After closing that document
![Capture d’écran 2019-12-05 à 13 28 00](https://user-images.githubusercontent.com/1617871/70236735-d0c61680-1765-11ea-9834-49118e1650f3.png)
After opening a non void document followed by the opening of a void document
![Capture d’écran 2019-12-05 à 13 35 32](https://user-images.githubusercontent.com/1617871/70236766-df143280-1765-11ea-873d-3047ee1ad325.png)
HTH

**Comment by jlaurens** [comment]
Hi Stefan,

this is probably related to bug #879 (about void documents) that you have already fixed. Maybe I should try the new version because it may have fixed this bug as side effect. Hope I'l find some time for that...

**Comment by stloeffler** [comment]
I think I finally found a workaround for what appears to be [QTBUG-17941](https://bugreports.qt.io/browse/QTBUG-17941).
