### ISSUE TITLE
Opening a void document does not work

### ISSUE THREAD

**Issue by jlaurens** [TeXworks/texworks#879]
**Bug description:**

TW does not allow to open a void document

**Steps to reproduce the problem:**

1. Create a void `foo.tex` document
2. Open TW
3. Open `foo.tex`: nothing happens
4. Add some content to `foo.tex` from an external editor
5. Open `foo.tex` from TW: it works

**Expected behavior:**

Open documents even if their contents is void

**General information:**
_TeXworks version_: 0.6.3
_TeXworks obtained from_: Sourceforge
_Operating system_: OSX 10.13.6

**Additional information:**

**Comment by stloeffler** [comment]
This should have been fixed in the current development version (in 71f0998158880433c44fe521d8b4d0d2b0aec85f)
