### ISSUE TITLE
macOS: Texworks cannot start compiling because setting of log file failed (spaces in path)

### ISSUE THREAD

**Issue by Toru47** [TeXworks/texworks#882]
**Bug description:**
log4cxx: setFile(/Users/lkn/Library/Application Support/MiKTeX/texmfs/data/miktex/log/pdflatex.log,true) call failed.
log4cxx: IO Exception : status code = 13
log4cxx: No output stream or file set for the appender named [RollingLogFile].
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (MiKTeX 2.9.7250)

Sorry, but /usr/local/bin/pdflatex did not succeed.

**Steps to reproduce the problem:**

1. Create a new tex file
2. Open the log console
3. Try to compile
4. Look into log console

**Expected behavior:**
No error.

**General information:**
_TeXworks version_: 0.6.3 (travis-ci)
_TeXworks obtained from_: GitHub
_Operating system_: macOS 10.15.2 (19C57)

**Additional information:**
There're spaces in file path but the program should have no problems with it. The problem in the path above is the part "Application Support".

**Comment by stloeffler** [comment]
This seems to be a MiKTeX issue as TeXworks doesn't use anything named `log4cxx` or `RollingLogFile` and doesn't access the specified path AFAIK.
Does running `pdflatex` from the terminal (and not from TeXworks) produce the same problem?

From https://github.com/smartdevicelink/sdl_core/issues/809, it might be a permissions problem...
