### ISSUE TITLE
Segfault in Poppler::Page::transition when opening tex document

### ISSUE THREAD

**Issue by devreal** [TeXworks/texworks#884]
**Bug description:**

Under certain circumstances Texworks crashes when opening a LaTeX file. It appeared both with a Beamer presentation and with a subchapter of my thesis document (other chapters and the main document were already opened).

I was able to reproduce it with an installation from the latest-build ppa (`0.7~201912010942~git~bafff42-bionic`), however I didn't see a dbgsym package for it so I got the following stack trace from the stable ppa (`TeXworks 0.6.2 (Debian) [r.7ecce17, 4/29/17 6:23 PM]`)
```
(gdb) bt
#0  Poppler::Page::transition (this=0x0) at ./qt5/src/poppler-page.cc:774
#1  0x00005555556bb814 in QtPDF::Backend::PopplerQt::Page::loadTransitionData (this=this@entry=0x55555691e490) at ./modules/QtPDF/src/backends/PopplerQtBackend.cpp:794
#2  0x00005555556c0287 in QtPDF::Backend::PopplerQt::Page::Page (this=0x55555691e490, parent=<optimized out>, at=<optimized out>, docLock=...)
    at ./modules/QtPDF/src/backends/PopplerQtBackend.cpp:488
#3  0x00005555556c050e in QtPDF::Backend::PopplerQt::Document::page (this=0x5555567cc940, at=<optimized out>) at ./modules/QtPDF/src/backends/PopplerQtBackend.cpp:287
#4  0x0000555555698b7f in QtPDF::PDFDocumentScene::reinitializeScene (this=this@entry=0x555556900780) at ./modules/QtPDF/src/PDFDocumentView.cpp:2013
#5  0x000055555569a8c5 in QtPDF::PDFDocumentScene::PDFDocumentScene (this=0x555556900780, a_doc=..., parent=<optimized out>, dpiX=<optimized out>, dpiY=<optimized out>)
    at ./modules/QtPDF/src/PDFDocumentView.cpp:1818
#6  0x00005555556a5a6c in QtPDF::PDFDocumentWidget::load (this=<optimized out>, filename=...) at ./modules/QtPDF/src/PDFDocumentWidget.cpp:74
#7  0x00005555555fcaad in PDFDocument::reload (this=this@entry=0x5555566c82f0) at ./src/PDFDocument.cpp:408
#8  0x00005555556000d3 in PDFDocument::loadFile (this=this@entry=0x5555566c82f0, fileName=...) at ./src/PDFDocument.cpp:400
#9  0x0000555555601c38 in PDFDocument::PDFDocument (this=0x5555566c82f0, fileName=..., texDoc=0x555555da0000) at ./src/PDFDocument.cpp:80
#10 0x000055555565d74b in TeXDocument::openPdfIfAvailable (this=this@entry=0x555555da0000, show=show@entry=false) at ./src/TeXDocument.cpp:1341
#11 0x000055555566b75b in TeXDocument::loadFile (this=this@entry=0x555555da0000, fileName=..., asTemplate=asTemplate@entry=false, inBackground=inBackground@entry=false, 
    reload=reload@entry=false, forceCodec=forceCodec@entry=0x0) at ./src/TeXDocument.cpp:1096
#12 0x000055555566bb85 in TeXDocument::TeXDocument (this=0x555555da0000, fileName=..., asTemplate=<optimized out>) at ./src/TeXDocument.cpp:85
#13 0x000055555566bf44 in TeXDocument::openDocument (fileName=..., activate=<optimized out>, raiseWindow=<optimized out>, lineNo=-1, selStart=0, selEnd=0) at ./src/TeXDocument.cpp:639
#14 0x00005555556208bc in TWApp::event (this=0x7fffffffdcb0, event=<optimized out>) at ./src/TWApp.cpp:804
#15 0x00007ffff663a83c in QApplicationPrivate::notify_helper (this=this@entry=0x555555b86470, receiver=receiver@entry=0x7fffffffdcb0, e=e@entry=0x555555df0ca0) at kernel/qapplication.cpp:3722
#16 0x00007ffff6642104 in QApplication::notify (this=0x7fffffffdcb0, receiver=0x7fffffffdcb0, e=0x555555df0ca0) at kernel/qapplication.cpp:3481
#17 0x00007ffff58bc9c8 in QCoreApplication::notifyInternal2 (receiver=0x7fffffffdcb0, event=event@entry=0x555555df0ca0) at kernel/qcoreapplication.cpp:1024
#18 0x00007ffff58bf13d in QCoreApplication::sendEvent (event=0x555555df0ca0, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:233
#19 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x555555b865e0) at kernel/qcoreapplication.cpp:1699
#20 0x00007ffff58bf6c8 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1553
#21 0x00007ffff5916353 in postEventSourceDispatch (s=0x555555bc4be0) at kernel/qeventdispatcher_glib.cpp:276
#22 0x00007ffff275a417 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#23 0x00007ffff275a650 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#24 0x00007ffff275a6dc in g_main_context_iteration () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff591597f in QEventDispatcherGlib::processEvents (this=0x555555bd2970, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#26 0x00007ffff58ba9fa in QEventLoop::exec (this=this@entry=0x7fffffffd9b0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#27 0x00007ffff58c3aa4 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1297
#28 0x00005555555e287a in main (argc=<optimized out>, argv=<optimized out>) at ./src/main.cpp:180
```

**General information:**
_TeXworks version_: TeXworks 0.6.2 (Debian) [r.7ecce17, 4/29/17 6:23 PM]
_TeXworks obtained from_: stable ppa
_Operating system_: Linux Mint 19.2

**Additional information:**

After deleting all temporary files I can open the file again. I'm not sure what exactly triggers this issue so I cannot create a small reproducer.

Please let me know if I can provide any additional information that can help solve this problem.

**Comment by stloeffler** [comment]
Thanks for the detailed bug report.
There should be a dbgsym package in the latest-build ppa now (you need to add the main/debug channel to the apt sources list). Could you retry with the latest version?

Some general information: it seems that during loading the pages, at some point Tw gets an invalid (null) pointer from the underlying poppler framework. It then naturally crashes when it tries to dereference it. Since Tw performs several checks that the requested page is in a valid range, it should never get null pointers. Checking for that specific condition (is null) would be possible, but then Tw would likely simply crash somewhere else when using the pointer. I'd much rather identify and fix the underlying issue.
The fact that the problem does not seem to be reproducible reliably may hint at it being related to multithreading (e.g. a race condition). However, at this early stage of loading, there shouldn't be much multithreaded processing going on yet.

It might be helpful if you could answer the following questions:
 * Does the problem appear only on large PDFs (e.g., many pages and/or large file size) or also on small ones (e.g., 1-2 pages, text-only)?
 * When the problem occurs, is it reproducible for that file (i.e., without doing anything like deleting temp files etc., if you close Tw and reopen the pdf, does it occur again)?
 * I assume the problem occurs also if you load the PDF directly (rather than loading a TeX that then automatically loads the PDF as in the backtrace)?
 * As it occurs both with a beamer presentation and a thesis chapter, I assume there are no fancy shenanigans (e.g. page transitions such as dissolve or swipe, annotations such as editing markings or comments, etc.) that appear in both documents?

**Comment by devreal** [comment]
@stloeffler Thanks a lot for your feedback. I will gather more information the next time this issue occurs. So far, I have not seen it happening again (partly because I have not written much LaTeX recently but will pick up again over the coming weeks). 

Some comments to your questions:

> Does the problem appear only on large PDFs (e.g., many pages and/or large file size) or also on small ones (e.g., 1-2 pages, text-only)?

The PDFs were fairly large, yes (a couple dozen pages or so). I haven't seen this happening on short PDFs but most of my documents grow larger than a few pages.

> When the problem occurs, is it reproducible for that file (i.e., without doing anything like deleting temp files etc., if you close Tw and reopen the pdf, does it occur again)?

It is, yes. Tw crashes every time I try to open the tex file.

> I assume the problem occurs also if you load the PDF directly (rather than loading a TeX that then automatically loads the PDF as in the backtrace)?

I have not tried that, will do next time it occurs.

> As it occurs both with a beamer presentation and a thesis chapter, I assume there are no fancy shenanigans (e.g. page transitions such as dissolve or swipe, annotations such as editing markings or comments, etc.) that appear in both documents?

Correct, my thesis chapter does not contain much fanciness such as page transitions, only static figures, text, and references.

Given the fact that cleaning the temporary files fixes the problem, my guess is that one of them gets corrupted for some reason. In that case I guess the only thing Tw could do is to error out gracefully and ask the user to delete the temporary files. I will also make a copy of the temporaries for you to look at, if that helps.

**Comment by stloeffler** [comment]
Could you try with the latest dev build (dated 20200615 or later) - hopefully this issue is fixed.

**Comment by stloeffler** [comment]
Closed due to inactivity
