### ISSUE TITLE
PDF in the build-in viewer looks fuzzy

### ISSUE THREAD

**Issue by xpsair** [TeXworks/texworks#892]
**Bug description:**
Build-in viewer has a fuzzy pdf rendering

**Steps to reproduce the problem:**

1. get IEEE latex template from https://www.ieee.org/content/dam/ieee-org/ieee/web/org/pubs/conference-latex-template_10-17-19.zip
2. typeset with pdfLaTeX engine
3. build-in PDF viewer shows this fuzzy looks compared to Skim

**Expected behavior:**
PDF shows a clear view

**General information:**
_TeXworks version_: `0.6.3 (tarvis-ci) [r.a2470ca, 2019/3/17 1:06 AM]` and `0.7 ("personal") [r.641fd0c7, 2020/2/22/ 9:14 PM]`
_TeXworks obtained from_: .dmg version 0.6.3 from https://github.com/TeXworks/texworks/releases
_Operating system_: macOS High Sierra 10.13.6 (17G11023)

**Additional information:**
<img width="1440" alt="Snipaste_2020-03-08_14-10-30" src="https://user-images.githubusercontent.com/3363680/76157761-719ee600-6148-11ea-9f77-4cdd3d81ac39.png">

**TeX installation infomation**
```
dpi: 72
which pdflatex: /usr/local/bin/pdflatex

PDFLATEX: pdflatex -version
pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2018)
kpathsea version 6.3.0
Copyright 2018 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.34; using libpng 1.6.34
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with xpdf version 4.00

Environment variables:
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.7RX0VaD4G5/Render
HOME=/Users/abc
LOGNAME=abc
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/texlive/2012/bin/x86_64-darwin
SHELL=/bin/bash
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.MkyCoFNoV0/Listeners
TMPDIR=/var/folders/b8/6nwnn_bn4yd7bzkg5ms14y0m0000gn/T/
USER=abc
XPC_FLAGS=0x0
XPC_SERVICE_NAME=texstudio.89700
__CF_USER_TEXT_ENCODING=0x1F5:0:0

TeXstudio:
Path        : /Applications/texstudio.app/Contents/MacOS/texstudio
Program call: /Applications/texstudio.app/Contents/MacOS/texstudio
Setting file: /Users/abc/.config/texstudio/texstudio.ini

Command configuration in TeXstudio:
    Precompile (pre-compile): 
    PDF Viewer (view-pdf): txs:///view-pdf-internal --embedded
    PDF Chain (pdf-chain): txs:///pdflatex | txs:///view-pdf
    BibTeX 8-Bit (bibtex8): bibtex8 %.aux
    PS Chain (ps-chain): txs:///latex | txs:///dvips | txs:///view-ps
    SVNADMIN (svnadmin): svnadmin 
    Internal Precompile (internal-pre-compile): txs:///pre-compile | txs:///conditionally-recompile-bibliography
    Makeglossaries (makeglossaries): makeglossaries %
    DviPs (dvips): dvips -o %.ps %.dvi
    LaTeX (latex) (r): latex -src -interaction=nonstopmode %.tex
    Build & View (quick): txs:///compile | txs:///view
    Default Index Tool (index): txs:///makeindex
    Latexmk (latexmk): latexmk -pdf -silent -synctex=1 %
    PS Viewer (view-ps): open %.ps > /dev/null
    PdfLaTeX (pdflatex) (r): pdflatex -synctex=1 -interaction=nonstopmode %.tex
    DVI Viewer (view-dvi): open %.dvi > /dev/null
    Default Bibliography Tool (bibliography): txs:///bibtex
    DVI->PS->PDF Chain (dvi-ps-pdf-chain): txs:///latex | txs:///dvips | txs:///ps2pdf | txs:///view-pdf
    XeLaTeX (xelatex) (r): xelatex -synctex=1 -interaction=nonstopmode %.tex
    Asymptote DVI Chain (asy-dvi-chain): txs:///latex | txs:///asy | txs:///latex | txs:///view-dvi
    SVN (svn): svn 
    Asymptote PDF Chain (asy-pdf-chain): txs:///pdflatex | txs:///asy | txs:///pdflatex | txs:///view-pdf
    DviPdf (dvipdf): dvipdfmx %.dvi
    Default Glossary Tool (glossary): txs:///makeglossaries
    Metapost (metapost): mpost -interaction=nonstopmode ?me)
    Asymptote (asy): asy ?m*.asy
    External PDF Viewer (view-pdf-external): open %.pdf > /dev/null
    DVI->PDF Chain (dvi-pdf-chain): txs:///latex | txs:///dvipdf | txs:///view-pdf
    Biber (biber): biber %
    Ghostscript (gs): gs "?am.ps"
    BibTeX (bibtex): bibtex %.aux
    DVI Chain (dvi-chain): txs:///latex | txs:///view-dvi
    Default Viewer (view): txs:///view-pdf
    Texindy (texindy): texindy %.idx
    LuaLaTeX (lualatex) (r): lualatex -synctex=1 -interaction=nonstopmode %.tex
    Default Compiler (compile) (r): txs:///xelatex
    Ps2Pdf (ps2pdf): ps2pdf %.ps
    Recompile Bibliography (recompile-bibliography): txs:///compile | txs:///bibliography | txs:///compile
    DviPng (dvipng): dvipng -T tight -D 120 %.dvi
    Makeindex (makeindex): makeindex %.idx

Additional Search Paths:
    Command: /usr/local/texlive/2012/bin/x86_64-darwin
    Log: 
    Pdf: 
```

**Comment by stloeffler** [comment]
Thanks for reporting. Could you please answer the following additional questions:
1. I assume you have a Retina display - correct?
2. Can you try running TeXworks (0.7) after setting the `QT_SCALE_FACTOR` environment variable to `1`? (note that this may make the icons very small - that's a different issue to be dealt with once we can confirm that the pdf rendering issue is fixed)
3. Assuming step 2 worked, how is the rendering performance (i.e. is TeXworks noticeably slow when displaying the pdf)?

Unfortunately, I don't have a Mac or Retina-like display to test all this myself.

**Comment by xpsair** [comment]
Thanks for your prompt reply :) Of course.
1. You're right, with MacBook Pro (Retina, 15-inch, Mid 2015).
2. I set `QT_SCALE_FACTOR` to 1 both in the `src/CMakeLists.txt` and `/etc/profile`, and rebuild TeXworks (0.7)
The TeXworks icons becomes a little bit but acceptable smaller.
3. Well, I don't think there is a noticable rendering performance difference.


It seems that `QT_SCALE_FACTOR` doesn't work on TeXworks (0.7) :(

<img width="1440" alt="Snipaste_2020-03-09_19-26-19" src="https://user-images.githubusercontent.com/3363680/76209184-3d0c5680-623c-11ea-913f-44d90ca70877.png">


Here is my `cmake ..` logs in case for any help.
```
localhost:build abc$ cmake ..
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Git commit info updated
-- Found ZLIB: /usr/lib/libz.dylib (found version "1.2.11")
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
-- Found Hunspell: /usr/local/Cellar/hunspell/1.7.0_2/lib/libhunspell-1.7.dylib
-- Found Lua: /usr/local/lib/liblua5.1.dylib (found version "5.1.5")
-- Found Poppler private headers: /usr/local/Cellar/poppler/0.76.1/include/poppler
-- Found Poppler_qt5: /usr/local/Cellar/poppler/0.76.1/lib/libpoppler-qt5.dylib (found version "0.76.1")
-- Found Poppler: /usr/local/Cellar/poppler/0.76.1/lib/libpoppler.dylib (found version "0.76.1") found components: qt5
-- Found Fontconfig: /usr/local/Cellar/fontconfig/2.13.1/lib/libfontconfig.dylib
-- Performing Test POPPLER_HAS_SEARCH_FLAGS
-- Performing Test POPPLER_HAS_SEARCH_FLAGS - Success
-- Performing Test POPPLER_HAS_DURATION_REAL
-- Performing Test POPPLER_HAS_DURATION_REAL - Success
-- Performing Test POPPLER_GLOBALPARAMS_IS_UNIQUE
-- Performing Test POPPLER_GLOBALPARAMS_IS_UNIQUE - Failed
QtPDF has been configured:

  Version:                             0.1
  Qt version:                          5.12.3
  Compiler optimization:               Release

  Poppler-Qt backend:                  yes
  MuPDF backend:                       no
  Shared library:                      yes
  Viewer application:                  no

  QtPDF will be installed to:
      /Applications

CMake Warning (dev) at modules/QtPDF/CMake/Modules/TranslationMacros.cmake:70 (message):
  create_qt_pro_file got two icns files:
  /Users/abc/git/texworks/TeXworks-doc.icns and
  /Users/abc/git/texworks/TeXworks.icns.  Ignoring the latter.
Call Stack (most recent call first):
  modules/QtPDF/CMake/Modules/TranslationMacros.cmake:19 (create_qt_pro_file)
  src/CMakeLists.txt:203 (target_add_qt_translations)
This warning is for project developers.  Use -Wno-dev to suppress it.

TeXworks has been configured:

  Version:                             0.7.0
  Git Commit:                          641fd0c7 (2020-02-22 14:14:10 +0100)
  Build ID:                            personal
  Qt version:                          5.12.3
  Compiler optimization:               Release

  Lua scripting plugin:                yes
  Python scripting plugin:             no
    OS X system python:                yes

  TeXworks will be installed to:
      /Applications

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/abc/git/texworks/build
```

**Comment by stloeffler** [comment]
Can you try recompiling and running with the following patch (both with and without the `QT_SCALE_FACTOR`)? Does this change/enhance anything?

[devicePixelRatio-patch.txt](https://github.com/TeXworks/texworks/files/4313614/devicePixelRatio-patch.txt)

**Comment by stloeffler** [comment]
Alternatively, here's another patch (that additionally sets some high-dpi flags in the source code).

[devicePixelRatio-patch2.txt](https://github.com/TeXworks/texworks/files/4314276/devicePixelRatio-patch2.txt)

**Comment by stloeffler** [comment]
Alternatively, here's another patch (that additionally sets some high-dpi flags in the source code).

[devicePixelRatio-patch2.txt](https://github.com/TeXworks/texworks/files/4314468/devicePixelRatio-patch2.txt)

**Comment by xpsair** [comment]
Thanks for your patient.

1. Patching `devicePixelRatio-patch.txt`, the viewer looks clear both with/without `QT_SCALE_FACTOR=1`, but the page is not shown completely.

2. Appending updates in the `src/main.cpp` from `devicePixelRatio-patch2.txt` makes no difference with/without `QT_SCALE_FACTOR=1`.

Your patches work on the rendering resolution problem 👍, but now the viewer has the problem of showing incomplete pages :(
<img width="1440" alt="Snipaste_2020-03-12_11-15-45" src="https://user-images.githubusercontent.com/3363680/76484040-ab773180-6453-11ea-826c-d3e7b9fb82bd.png">

**Comment by stloeffler** [comment]
Thanks for testing. Apparently, only a quarter of each tile is rendered - this should look even weirder, if you make the pdf window larger (e.g. maximize it) and zoom in (such that more than one tile is visible).

Anyway, here's a modified patch that should hopefully fix this issue...

[devicePixelRatio-patch3.txt](https://github.com/TeXworks/texworks/files/4323450/devicePixelRatio-patch3.txt)

**Comment by xpsair** [comment]
Thanks for your work!
Your guess is right about patches `devicePixelRatio-patch.txt` and `devicePixelRatio-patch2.txt`.
If zoon in 40%, it looks ok, except the magnifying glass function.
<img width="1440" alt="2 40%" src="https://user-images.githubusercontent.com/3363680/76521616-20705880-64a0-11ea-88a5-c1d7824c3b89.png">

<img width="1440" alt="2 50%" src="https://user-images.githubusercontent.com/3363680/76521634-2a925700-64a0-11ea-81e8-51502527c414.png">


However, `devicePixelRatio-patch3.txt` causes more trouble...
<img width="1440" alt="3 40%" src="https://user-images.githubusercontent.com/3363680/76521661-38e07300-64a0-11ea-9ef3-87639e3608ed.png">

<img width="1440" alt="3 150%" src="https://user-images.githubusercontent.com/3363680/76521678-45fd6200-64a0-11ea-844f-85ec37dc2f3b.png">

I hope fixing this issue don't take too much of your time :)

**Comment by stloeffler** [comment]
Thanks for testing and for the screenshots. Here is another attempt (unfortunately, not being able to test this myself dynamically makes fixing this considerably harder than it would be if I could just try changes and see directly what they are doing...)

[devicePixelRatio-patch4.txt](https://github.com/TeXworks/texworks/files/4324595/devicePixelRatio-patch4.txt)

**Comment by xpsair** [comment]
I really appreciate your efforts on this issue!
I'm glad to do something to help make TeXworks better.

Your `devicePixelRatio-patch4.txt` works! This rendering improvement comforts TeXworks users a lot! 
<img width="1440" alt="Snipaste_2020-03-13_09-54-48" src="https://user-images.githubusercontent.com/3363680/76582522-6e717480-6511-11ea-9840-485fcb43c062.png">


Thank you @stloeffler 👍

**Comment by stloeffler** [comment]
Thanks again for testing and the extensive screenshots - they helped a lot!

**Comment by stloeffler** [comment]
FYI, 1d1f0678231983a3a8d32c6b3700f1da8d555ed9 introduced high-res icons as well - so the overall experience should be better now.
