### ISSUE TITLE
Bug: ptex2pdf cannot run normally on TeXworks 0.6.3 or above (macOS)

### ISSUE THREAD

**Issue by MOhkura** [TeXworks/texworks#897]
**Bug description:**
ptex2pdf cannot run normally. The following error message appears:
env: texlua: No such file or directory

**Steps to reproduce the problem:**
Add a new typeset for ptex2pdf -u -l -ot -synctex=1 -file-line-error
Write a simple TeX source
Run typeset of ptes2pdf

**Expected behavior:**
Compile TeX source and generate a PDF file.

**General information:**
TeXworks version: 0.6.3 or above
TeXworks obtained from: http://www.tug.org/texworks/
Operating system: macOS 10.15.4

**Additional information:**
I can compile a TeX source using both TeXShop and Terminal.app. Further, I can also compile the TeX source using TeXworks 0.6.2 without any errors. So, I believe there is an issue on TeXworks 0.6.3 or above.

**Comment by stloeffler** [comment]
Thanks for reporting this issue. This is probably related how the underlying Qt framework (and the OS itself) handle environment variables (in particular $PATH). Does any of the workarounds linked in #861 resolve the problem?

**Comment by MOhkura** [comment]
Hi Stloeffler,

Thank you for your reply. When I launched TeXworks 0.6.5 from Terminal.app, ptex2pdf can run normally. On the other hand, the error message still appeared when I edited Info.plist and launched TeXworks from Finder. So, I will use TeXworks launched from Terminal.

**Comment by stloeffler** [comment]
Could you try a typesetting tool with
Program to run: /bin/sh
Arguments:
 * -c
 * ptex2pdf -u -l -ot -synctex=1 -file-line-error $fullname

This should run everything through a terminal/shell explicitly, thereby hopefully setting the environment variables correctly.

**Comment by MOhkura** [comment]
Unfortunately, the following message appeared when I launched TeXworks from Finder:
/bin/sh: ptex2pdf: command not found
It worked fine when TeXworks was launched from Terminal.
