### ISSUE TITLE
texworks finds almost no templates.

### ISSUE THREAD

**Issue by stolk** [TeXworks/texworks#898]
**Bug description:**

tetex, as installed with Ubuntu 18.04 will find almost no templates.

**Steps to reproduce the problem:**

1. `$  sudo apt-get install texworks` 
2.` $ sudo apt-get install texlive-xetex`
3. `$ sudo apt-get install texlive-publishers`
4. `$ texworks`
5. File >> New From Template ...

![image](https://user-images.githubusercontent.com/455280/83043554-df480900-9ff7-11ea-8fd4-526bd608a953.png)

**Expected behavior:**

Styles for books, reports, etc.

**General information:**
_TeXworks version_: 0.6.2 (Debian) [r.7ecce17, 2017-04-29 9:23 AM]

_TeXworks obtained from_:  Ubuntu
_Operating system_:  Ubuntu

**Additional information:**

**Comment by stloeffler** [comment]
The templates you refer to are generic example files bundled with the editor (TeXworks), not (La)TeX class- or style-files as installed by, e.g., texlive-publishers. You can still use any installed classes and styles in your own files, there are just no pre-bundled examples.

That being said, contributions of example files (that are useful for a large group of users, i.e. that are not too specific) are always very welcome!
