### ISSUE TITLE
TeXworks.conf does not record. Format for manual preferences?

### ISSUE THREAD

**Issue by cargocultprog** [TeXworks/texworks#902]
**Bug description:**
Arch Linux ARM, with TeXLive 2020 from internet install to /usr/local/texlive/2020, rather than the system package install. TeXworks 0.6.5 from system package manager. Correctly compiles known-good *.tex. No problem there. But I cannot save preferences. Directory ~/.config/TUG exists and is writeable, but no TeXworks.conf file there. If I manually add a blank writeable file, it does not help. When I open TeXWorks, Edit Preferences, OK, quit, the TeXWorks.conf file did not save data and is still empty. From within TeXWorks, Help, it correctly identifies the location of the preferences file, and can open my blank in a text editor. Perhaps if I knew the format of TeXWorks preferences, I could edit it manually? But I cannot find the preferences format documented.

**Steps to reproduce the problem:**

1. Open TeXWorks. Edit Preferences, make changes.
2. Quit TeXWorks and re-open it.
3. Preferences not saved. TeXworks.conf not written. Repeatable.

**Expected behavior:**
~/.config/TUG/TeXworks.conf should save preferences, and they should be used next time TeXWorks is launched.

**General information:**
_TeXworks version_: 0.6.5, via Arch Linux ARM package manager
_TeXworks obtained from_: TUG, 2020 via Internet install to /usr/local/texlive/2020
_Operating system_: Arch Linux ARM

**Additional information:**

**Comment by stloeffler** [comment]
Thanks for reporting. Unfortunately, I can't reproduce the issue with the latest development version (in a docker container, as I don't have an Arch installation). For me, it correctly creates `~/.config/TUG/TeXworks.conf` with the content
```[General]
defaultEngine=pdfLaTeX
```
(it's an ini format as it relies on Qt's QSettings object). The `defaultEngine` entry is a string containing one of the typesetting tools dropdown entries. There are many more possible keys, of course, but that should suffice for initial testing.

A few questions:
* Is there any output to the terminal if you start Tw from the command line?
* You don't have a file named `texworks-setup.ini` in the same directory as the texworks executable (to configure portable mode - although that should show in the Help menu dialog)
* You don't have a `TW_INIPATH` environment variable (again, this should show in the Help menu dialog)
* Can you remove the ~/.config/TUG directory (assuming it's empty except for the TeXworks.conf file you created)? Is it then recreated when starting Tw?

**Comment by cargocultprog** [comment]
1. If texworks is launched from terminal, I get the XDG_RUNTIME_DIR not set message. This is not unusual. If I manually create ~/.XDG with permissions 0700, and edit my login to export XDG_RUNTIME_DIR=~/.XDG, and re-boot, then I do not get that message. But it makes no difference.

2. I do not have that *.ini file anywhere. Installation is not portable.

3. echo $TW_INIPATH returns nothing. I do not see in the TeXworks help. There is a ~/.TeXworks directory, with a configuration subdirectory, but it is empty.

4. If I remove ~/.config/TUG, it is re-created when I relaunch texworks. But it remains empty whether or not I try to set preferences.

THE GOOD NEWS:

TeX works is able to read ~/.config/TUG/TeXworks.conf and apply the data, if I manually write it from an external text editor. For example, I wrote defaultEngine=LuaLaTeX there, and it is correctly applied when I next launch TeXworks.

The problem seems limited to my own setup. But what I really need to know is the format of the TeXworks.conf file. It appears to be key-value pairs, but I do not know the possible keys or their possible values. Is this documented anywhere? Then I can manually set preferences.

**Comment by cargocultprog** [comment]
Further info: Now I compiled TeXworks from its GitHub source code, downloaded earlier today. No problem building. Rebooted, verified that `which texworks` leads to the compiled version in `/usr/local` instead of the version from package installer. Launched TeXworks, tried to change settings, closed TeXworks. Still no joy. The configuration file remains empty no matter what I do. Permissions are correct. But again, if I manually type text into the configuration file, then TeXworks can read it.

Perhaps there is some SELinux intercept, specific to my machine. Does not seem to be a general bug.

**Comment by stloeffler** [comment]
Interesting. The ~/.TeXworks subdirectories should not be empty, either. After my first launch, I got the subdirectories `completion` (with a bunch of .txt files), `configuration` (with a bunch of .txt files), `scripts` (with some subfolders and some .js, .py, .lua files), `translations` (empty), and the file TwFileVersions.db. If those don't exist or are not populated, something goes wrong in that setup step as well.
It might be interesting to test with either a `texworks-setup.ini` portable setup or by setting `TW_INIPATH` env var (e.g. to /tmp/) to see if the config file can be written then.
As far as available config options go, there unfortunately is no official documentation. To some extent, they are considered an implementation detail not intended to be changed "by hand" outside Tw. That being said, most of the settings can be found in the source code [src/PrefsDialog.cpp#L684-L855](https://github.com/TeXworks/texworks/blob/master/src/PrefsDialog.cpp#L684-L855). Look for lines saying "settings.setValue(", which take the key and value as arguments. Currently, all settings are under the "[General]" section. Boolean values are stored as the literal strings "true" and "false".
Note, though, that the conf file typically is used to store other data as well, such as recently opened files, etc., some of which is in a Qt-internal binary encoding. Such data will not be easy to handcraft, and doing so would likely not be worth the effort.

**Comment by cargocultprog** [comment]
TW_INIPATH did not help. Instead, I will read through the source code file, mentioned above. If that works for me, good. In the long term, when this "COVID shutdown" ends, I can copy the necessary data from TeXworks set to my preferences on a completely different machine, with different system. I know it works there.

Life's mysteries. Issue closed.

**Comment by cargocultprog** [comment]
Reopen, temporarily at least....

After reading through the source code, I have figured out how to manually write TeXworks.conf so that
it saves font family, and a variety of other preferences. But I am baffled as to how to save the editor font size. All my attempts at guessing key-value, for the source code, have failed. Apparently it is something mystical in Qt.

So, what is the key-value format for editor font size?

**Comment by stloeffler** [comment]
This is the format Qt uses to store font settings (i.e., it is not defined in the Tw source code but in Qt). It seems to be
```
font="FONTNAME,FONTSIZE"
```
e.g. (in my case)
```
font="Ubuntu Mono,12"
```
