### ISSUE TITLE
TeXworks is not working

### ISSUE THREAD

**Issue by skcvlsi** [TeXworks/texworks#903]
**Bug description:**
texify: security risk: running with elevated privileges
pdflatex: security risk: running with elevated privileges
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 20.6.29)
entering extended mode
(C:/Users/sai/Documents/skc3July2020.tex
LaTeX2e <2020-02-02> patch level 5
L3 programming layer <2020-06-18>
("C:\Program Files\MiKTeX 2.9\tex/latex/base\article.cls"
Document Class: article 2019/12/20 v1.4l Standard LaTeX document class
("C:\Program Files\MiKTeX 2.9\tex/latex/base\size10.clo"))
! Undefined control sequence.
<recently read> \userpackage 
                             
l.3 \userpackage
                {lipsum}
? 

**Steps to reproduce the problem:**

1. 
2. 
3. 

**Expected behavior:**

**General information:**
_TeXworks version_: 0.6.5
_TeXworks obtained from_: MiKTex
_Operating system_: Window 7_64 bit

**Additional information:**

**Comment by stloeffler** [comment]
This is not a Tw bug - you have an error in your code. It's supposed to be `\usepackage`.
