### ISSUE TITLE
TeXworks does not refresh the PDF if the TeX file sits in a root directory.

### ISSUE THREAD

**Issue by UweZiegenhagen** [TeXworks/texworks#908]
**Bug description:**

TeXworks does not refresh the PDF if the TeX file has been put in a root directory, e.g. C:\ or r:\

**Steps to reproduce the problem:**

1. Create a TeX file and save it in the root directory of a drive. 
2. Compile the file, the initial PDF shows correctly.
3. Change the TeX file, compile again, TeXworks still shows the old PDF and does not update.
4. Save the file into some subdirectory of the drive, amending the TeX and compiling now results in an updating PDF.

It also does shows the behavior if you reverse the process:

1. Start with a LaTeX file in a subdirectory. Recompiling the file always results in an updated PDF. Save the file in one of the top directories and the refresh stops.

**Expected behavior:**

* PDF is refreshed regardless of where the TeX file sits, top directory or not.

**General information:**
_TeXworks version_:  0.6.5
_TeXworks obtained from_: TeX Live 2020
_Operating system_: Windows 10 Pro

**Additional information:**

See the thread here https://tex.stackexchange.com/questions/568368/texworks-pdf-not-refreshing

**Comment by stloeffler** [comment]
Thanks for reporting. This should be fixed in the latest development version.
