### ISSUE TITLE
TeXworks does not compile with Qt 5.15.1

### ISSUE THREAD

**Issue by jakobjakobson13** [TeXworks/texworks#909]
**Bug description:**
TeXworks does not compile with Qt 5.15.1.

**Steps to reproduce the problem:**
See [https://github.com/flathub/org.tug.texworks/pull/5](https://github.com/flathub/org.tug.texworks/pull/5)

**Expected behavior:**
Compiles normally.

**General information:**
_TeXworks version_:  0.6.5
_TeXworks obtained from_: Git/Flathub
_Operating system_: Linux

**Additional information:**
If you consider this failure as not important, you can just close this bug.

**Comment by stloeffler** [comment]
The current development version does compile under Qt 5.15.1 (see https://github.com/TeXworks/texworks/runs/1355125152?check_suite_focus=true#step:4:60, which uses Homebrew, which has Qt 5.15.1) and even Qt 6 (see https://github.com/TeXworks/texworks/runs/1355125275?check_suite_focus=true#step:3:1006).

The latest stable version (0.6.5) did not as it predates the release of Qt 5.15, but the next one will.
