### ISSUE TITLE
TeXWorks doesn't open on MacOS BigSur

### ISSUE THREAD

**Issue by DaleTurley** [TeXworks/texworks#915]
I recently updated my Macbook to MacOS Big Sur. Now, the TeXworks GUI doesn't open.

When the application is opened, either from Applications or clicking on an associated file, the icon appears in the icon try but nothing happens. After a couple of seconds, when you right click on the icon you get the option to force close.
If you watch activity monitor, the RAM is allocated at 1.5GB and the CPU is at 100%.
If you leave it for several minutes nothing else happens, but the fan starts to kick in.

I am using a Macbook Pro 2019, 1.4 GHz with 8GB RAM. My OS version is 11.0.1.

**Comment by rwe121** [comment]
I had the same problem with TeXworks 0.6.5 and Mac OS 11.0.1. I was able to open TeXworks in OS 11.0.1 by reverting to TeXworks version 0.6.3

**Comment by stloeffler** [comment]
0.6.5 was built with a combination of Xcode and Qt which does not work on BigSur. The current development binaries (as well as future stable releases) should work (see #905).
