### ISSUE TITLE
Trying to run on MacOS 11.1 Big Sur

### ISSUE THREAD

**Issue by dcconn** [TeXworks/texworks#922]
When trying to run on MacOS 11.1 Big Sur, TeXworks hangs and does nothing else - even after several hours. It always needs to be forced to quit.

**Comment by Groggles0** [comment]
Been finding this as well, have Big Sur installed on my Macbook. The application appears in the taskbar at the bottom but the application itself fails to load.

**Comment by stloeffler** [comment]
I presume you are referring to TeXworks 0.6.5? 0.6.5 was built with a combination of Xcode and Qt which does not work on BigSur. The current development binaries (as well as future stable releases) should work (see #905).

**Comment by dcconn** [comment]
@stloeffler Thanks so much :)

This version works on Big Sur (v11.0.1) and also on Big Sur v11.2: https://bintray.com/texworks/OSX-latest/download_file?file_path=TeXworks-osx-0.7-202011160643-git_14dcc2c.dmg
