### ISSUE TITLE
Impossible to launch TeXworks 0.6.5 or 0.6.4 on macOS Big Sur

### ISSUE THREAD

**Issue by ramuntcho** [TeXworks/texworks#923]
**Bug description:**
Impossible to launch TeXworks 0.6.4 and 0.6.5 on macOS Big Sur

**Steps to reproduce the problem:**

1. Right-clic to open TeXworks 0.6.4 or 0.6.5 (to avoid Gatekeeper).
2. The menu on the top of the screen appears, but no window and i have to make a force-quit
3. No problem with version 0.6.3

**Expected behavior:**

**General information:**
_TeXworks version_: 0.6.4 and 0.6.5
_TeXworks obtained from_: official site
_Operating system_: macOS 11.2

**Additional information:**

**Comment by stloeffler** [comment]
0.6.6 should work on BigSur now.
