### ISSUE TITLE
Drop FindLua.cmake module in favour of cmake's upstream module to support Lua 5.4

### ISSUE THREAD

**Issue by badshah400** [TeXworks/texworks#924]
**Bug description:**
The Lua scripting support for texworks on openSUSE stopped building when we switched to Lua 5.4 instead of 5.3. It turns out the [FindLua.cmake](https://github.com/TeXworks/texworks/blob/5bdad4e836e1afef7ccd8bd9a4ee92afd747235a/CMake/Modules/FindLua.cmake#L55) module bundled with texworks only supports lua up to version 5.3. On one hand it is easy to extend support to Lua 5.3 in this module, on the other cmake already includes the [FindLua](https://cmake.org/cmake/help/latest/module/FindLua.html) functionality since version 3.0. I would suggest dropping texwork's own module in favour of the upstream cmake one.

Dropping texwork's FindLua module automatically enables building the lua scripting plugin against lua 5.4.

**Steps to reproduce the problem:**

1.  Try building against Lua 5.4

**Expected behavior:**
Should build Lua scripting plugin when compiling against Lua 5.4.

**General information:**
_TeXworks version_: 0.6.5
_TeXworks obtained from_: Upstream source tarball
_Operating system_: openSUSE Tumbleweed, x86-64

**Comment by stloeffler** [comment]
Thanks for the suggestion - done. (The custom FindLua dated back to the time pre-3.0 CMake support was still required).

**Comment by badshah400** [comment]
Big thanks.
