### ISSUE TITLE
Spelling error in binary

### ISSUE THREAD

**Issue by hpreusse** [TeXworks/texworks#929]
**Bug description:**
When running lintian (from Debian project) I get the report that there are spelling errors in the source code, which end up in the resulting binary. I created a patch, which is [here](https://raw.githubusercontent.com/debian-tex/texworks/master/debian/patches/spelling_errors.diff). Further the *.qm files in trans/qt needs to be re-created to make the patch fully effective.

Let me know if you intend to integrate my patch. Thanks!

**General information:**
_TeXworks version_: 0.6.6
_TeXworks obtained from_: github.com
_Operating system_: Debian GNU Linux

**Comment by stloeffler** [comment]
I'd love to integrate your patch - thanks for the work. Let me know if you want to create a pull-request or if I should apply the patch as is.
