### ISSUE TITLE
line spacing does not work

### ISSUE THREAD

**Issue by yordiak** [TeXworks/texworks#930]
**Bug description:**

When I increase line spacing from eg 100% to 150%, the spacing between lines in the editor does not change.

**Expected behavior:**
lines in the editor are increased

**General information:**
_TeXworks version_:  0.6.6
_TeXworks obtained from_: github
_Operating system_:  win10 64bit

**Additional information:**

**Comment by stloeffler** [comment]
It works for me (after a restart, as hinted at in the note at the bottom of the preferences dialog.

**Comment by yordiak** [comment]
I tried to restart texworks the the line spacing did not change

**Comment by stloeffler** [comment]
OK, I could reproduce it now (it only occurs when loading an existing .tex file, not when creating a new one).

Thanks for reporting. It should be fixed in the latest development version.
