### ISSUE TITLE
0.6.6 doesn't work on MacOS 10.14.5.

### ISSUE THREAD

**Issue by Mulugruntz** [TeXworks/texworks#934]
**Bug description:**

The installer will not work. And If I still force it, then the app will not start. It says that >=10.15 is needed.
This is the kind of information that should appear somewhere near download links, I think.
And maybe for each version, the minimum requirement should be apparent. 

Unless the compatibility was not broken on purpose.

**General information:**
_TeXworks version_: 0.6.6
_TeXworks obtained from_: https://github.com/TeXworks/texworks/releases/download/release-0.6.6/TeXworks-macos-0.6.6-202103111124-git_24442ac.dmg
_Operating system_: Mac OS Mojave, 10.14.5

**Comment by stloeffler** [comment]
Thanks for reporting! The compatibility was not broken on purpose - it appears to be a side effect of how the packages are currently built (using homebrew on Github Actions, which uses macOS 10.15). Note that I'm not a Mac user myself, so noticing, debugging and fixing such build issues is quite cumbersome.
Anyway, could you possibly give https://github.com/stloeffler/texworks-testing/releases/tag/717d3f7 a try and see if this starts up and looks and behaves correctly?

**Comment by Mulugruntz** [comment]
Thanks @stloeffler as it seems to work correctly now :-)
I added a comment to your commit https://github.com/stloeffler/texworks-testing/commit/717d3f719e5e142414f000910bfc345b479c517b even though it was there before.

**Comment by stloeffler** [comment]
Excellent - thanks for testing. I will need to do some cleanup and look into the "missing fonts" issue, but then I'll merge it into the main codebase here.
