### ISSUE TITLE
black mode background bug (Big Sur, M1 iMac)

### ISSUE THREAD

**Issue by coulmont** [TeXworks/texworks#939]
**Bug description:**

texWorks editor background is dark when macOS dark mode is on.

**Expected behavior:**
if dark mode is not implemented in texWorks, the background should no be dark.

**General information:**
_TeXworks version_: 0.6.6
_TeXworks obtained from_: 
_Operating system_: macOS Big Sur 11.4

**Additional information:**
<img width="755" alt="texworks" src="https://user-images.githubusercontent.com/4989509/120894424-90747c80-c618-11eb-8432-c6000f9c23ca.png">

**Comment by stloeffler** [comment]
Please clarify what you mean by "not implemented". The syntax highlighting scheme does not change (automatically), but that is in line with other applications such as the macOS Terminal app.
Admittedly, the color for `\usepackage` could be improved, but that can easily be customized as documented in the manual.

**Comment by coulmont** [comment]
Thanks, I will try to explain : 
with previous macOS versions, even in dark mode, the background stayed white, and the color scheme is adapted to this background,
with Big Sur on M1 iMac, the background isn't white anymore when the OS is in Dark Mode, but the color scheme isn't anymore adapted to this new background
I hope it is clearer now.

**Comment by stloeffler** [comment]
In the latest development version, I changed the coloring scheme so it should work with both light and dark themes now.
