### ISSUE TITLE
The symbol " is converted to double '

### ISSUE THREAD

**Issue by Carrataplan** [TeXworks/texworks#940]
**Bug description:**

The symbol " is converted to double '

**Steps to reproduce the problem:**

1. I try get the symbol "o umlaut" in Latex. E.g., Schr\"{o}dinger
2. For this purpose I type \"{o} in texworks
3. When I compile the tex file, the symbol " is automatically converted to double ' : " -> ''. It is almost indistinguishable in the source file, but I did not get a required umlaut in pdf file.

**Expected behavior:**

**General information:**
_TeXworks version_: 0.6.5
_TeXworks obtained from_: 
_Operating system_: windows 10

**Additional information:**

**Comment by stloeffler** [comment]
Thanks for reporting. This is sort of by-design when the "smart quotes" option is enabled (which, in "TeX ligatures" mode, replaces `"` by either ``` `` ``` or `''`). For your application, you can disable this behavior by clicking on Format > Smart Quotes > None.

I have improved the code slightly in that it no longer replaces `"` directly after `\`. I.e. the slightly more verbose, but more generally applicable `\"o` should be fine even with smart quotes enabled in the latest development version.
