### ISSUE TITLE
Crashes after compile if filename is containing non-ASCII Characters

### ISSUE THREAD

**Issue by LoveBodhi** [TeXworks/texworks#943]
**Bug description:**
When filename is containing non-ASCII Characters, after compile to PDF, Texworks instantly crashes, next time opening the same file still crash.

![Texworks_sucks](https://user-images.githubusercontent.com/37089530/130261583-7bbd5a09-d742-4d59-a3ba-156a510c0518.PNG)

**Steps to reproduce the problem:**

1. Enter any text
2. Saving with non-ASCII Characters
3. Click Compile

**Expected behavior:**
Instantly Crash, next time open the same file still crash

**General information:**
_TeXworks version_: 0.66
_TeXworks obtained from_: MikTex
_Operating system_: Windows 10

**Comment by stloeffler** [comment]
Thanks for reporting. This may be related to #938. Could you test with TeXworks obtained from this site (GitHub) as opposed to the one shipped by MiKTeX (to see if your issue is related to the MiKTeX modifications)?

**Comment by stloeffler** [comment]
Closed due to inactivity.
