### ISSUE TITLE
TexWorks keeps crashing

### ISSUE THREAD

**Issue by TimFH** [TeXworks/texworks#948]
**Bug description:**

TexWorks sporadically crashes without any error messages right after running a LuaLaTex job.

**Steps to reproduce the problem:**

1. Open a LaTex file.
2. Hit the green circle with the black triangle.
3. Wait for it to finish, and boom.

**Expected behavior:**

It doesn't crash.

**General information:**
_TeXworks version_:  Version 0.6.2 (Debian) [r.7ecce17, 4/29/17 12:23 PM]
_TeXworks obtained from_: ubuntu standard repository.
_Operating system_: Linux tims-17Z990-R-AAS9U1 5.4.0-81-generic #91~18.04.1-Ubuntu SMP Fri Jul 23 13:36:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux (latest version of ElementaryOS)

**Additional information:**

The only possibly relevant line I found in syslog was:

Nov  8 08:19:43 tims-17Z990-R-AAS9U1 gala.desktop[3009]: Window manager warning: Invalid WM_TRANSIENT_FOR window 0x5c00007 specified for 0x5c0006a (About TeXw).

**Comment by stloeffler** [comment]
Thanks for reporting. Two questions:
1) Does this happen with other tools (such as pdflatex, bibtex, ...)?
2) Does this happen with the latest development version (or the latest stable release), which are available at <https://launchpad.net/~texworks>

**Comment by stloeffler** [comment]
Closed due to inactivity
