### ISSUE TITLE
Crashes when clicking zoom

### ISSUE THREAD

**Issue by mayoutu1984** [TeXworks/texworks#953]
**Bug description:**
After compiling, I turn to the right lower corner of the pdf file and click zoom to make it from "100%" to "fit to width". After a couple of failed attempts, it crashes. It happened at least twice in the past few months.

**Steps to reproduce the problem:**
It seems to be a random problem so far. It has not happened frequently.

**Expected behavior:**
No crash.

**General information:**
_TeXworks version_: 0.6.6
_TeXworks obtained from_: github

_Operating system_: windows 10

**Additional information:**
None.

**Comment by stloeffler** [comment]
Thanks for reporting. Unfortunately, I couldn't reproduce it so far and therefore can't debug/fix it.
A couple of questions:
* What do you mean by "a couple of failed attempts"? Does the "Fit to width" fail?
* When it crashes and you reopen the same document again, does it crash again when zooming as described?
* Does it depend on the window size?
* Does it happen regardless of whether you use the widget in the status bar (bottom right corner), the toolbar, or the menu?
* Does it only happen with "fit to width" or also with other functions (such as "fit to window" or specifically with "fit to content width")?

**Comment by mayoutu1984** [comment]
> Thanks for reporting. Unfortunately, I couldn't reproduce it so far and therefore can't debug/fix it. A couple of questions:
> 
> * What do you mean by "a couple of failed attempts"? Does the "Fit to width" fail?
Yes, the failing always happened when I opened two or more tex files (together with the compiled pdf files), and today it crashed again just minutes ago (I opened the second file and clicked "Fit to width", there was no response, and after the second or third click, it crashed with all other files). Oftentimes, when I have multiple files opened, "Fit to width" works only for one pdf file, and for the others I have to use "ctrl+2" and it works.

> * When it crashes and you reopen the same document again, does it crash again when zooming as described?
I haven't encountered it before. The crashing is not that frequent.

> * Does it depend on the window size?
It crashed when the tex window and the pdf window are half and half.

> * Does it happen regardless of whether you use the widget in the status bar (bottom right corner), the toolbar, or the menu?
It happened only when I used the widget (bottom right corner). Actually I haven't used the toolbar or menu before for "Fit to width".

> * Does it only happen with "fit to width" or also with other functions (such as "fit to window" or specifically with "fit to content width")?
I cannot tell. I never tried fit to others before.

**Comment by stloeffler** [comment]
Thanks for your clarifications. That helped to find and fix the problem. The latest development binaries should now work as expected.
