### ISSUE TITLE
Customize color of cursor 

### ISSUE THREAD

**Issue by NailGit** [TeXworks/texworks#964]
Is it possible to make the possibility for change the color of the cursor? Now it is possible to change width, only. I tried to use file mystyle.css but I'm not a user of Qt and have had no success.

**Comment by stloeffler** [comment]
It seems that in current versions of Qt, [the cursor color is derived automatically](https://stackoverflow.com/a/55889624) from the background color and hence can't be changed individually, unfortunately.
