### ISSUE TITLE
pdf is unusable when typesetting

### ISSUE THREAD

**Issue by jlaurens** [TeXworks/texworks#968]
**Bug description:**

During typesetting, the new pdf file output is broken because it is under construct.
The old one is no longer available, except a pair of pages.
In comparison, if I open the pdf in apple's preview or acrobat reader DC it is still available during typesetting.

**Expected behavior:**
The old pdf should be still available until the new one is complete.

**General information:**
_TeXworks version_: 0.6.5
_TeXworks obtained from_: TL
_Operating system_: OSX 10.13.6

**Additional information:**

**Comment by khzimmer** [comment]
In my opinion this issue should not have a "bug" label.

The current implementation is not what you would like to see, so that's rather "Feature Wish" than a bug.
