### ISSUE TITLE
Cannot abort typesetting process after it finds an error

### ISSUE THREAD

**Issue by vdlee37** [TeXworks/texworks#974]
Hi, I recently migrated to 0.6.7 on windows 11, and noticed the following: when typesetting, the typesetting button used to turn from green to red for the duration of the process (in the previous release I used, not sure which one exactly). If an error was detected, the process could then be halted by hitting the button again.

This is no longer the case in 0.6.7. The only way to abort the process seems to be exiting from TeXworrks altogether, which leads to message: "A typesetting process is still running and must be stopped. Do you want to stop it now?"

Please let me know in case you require further info.

Thanks,
Matthé van der Lee

**Comment by stloeffler** [comment]
Sorry to hear you have this problem. I do indeed have a few questions:
* Does this happen when you start typesetting from the main document (i.e., usually the one with the `\documentclass`), from an included sub-document, or from a previously typeset pdf?
* Do you see the log output window anywhere?
* Does any typesetting icon in any TeXworks window change in any way (0.6.7 introduced a new state/icon (curved green arrow pointing down) to switch to the window in which the typesetting process is running in case you have a multi-file document)?
* Where are your files saved on the disk (e.g., on a physical hard disk, on a network file system, in a cloud, in a path/folder with spaces/non-ASCII characters, in a path that includes a symbolic link, ...)?
* Does the typesetting process start normally (i.e., are logs produced/changed, is the output produced/changed, etc.)?

HTH,
Stefan

**Comment by vdlee37** [comment]
Hi Stefan, thanks for looking into this.

I am using a main, single-file document, of which I attach some screen shots below. It is on my local hard disk, in a folder for which a symbolic link exists, There is a log output window. The typesetting icon does not change, neither in the main window nor in the associated PDF window (if it is open). The typesetting process works normally, and produces correct output, except that it cannot be terminated by means of the button when it pauses due to an error.

Matthé
![the document](https://user-images.githubusercontent.com/53441330/181268916-89dd5746-bb3a-4571-898e-188899472a9b.png)
![after typesetting finds an error](https://user-images.githubusercontent.com/53441330/181268977-f21cab81-7c10-472d-8977-d914db247aa1.png)
![after pressing the close-window button](https://user-images.githubusercontent.com/53441330/181269014-565c1b19-b0be-4930-9dbc-ee743d3fd6e0.png)

**Comment by vdlee37** [comment]
The last picture shows what happens when I hit the close-window button.

**Comment by vdlee37** [comment]
If the Windows build works correctly on other Windows 11 installations, there must be a problem with mine. In that case, how might I find out what causes it?

**Comment by vdlee37** [comment]
After reinstalling the latest versions of MikTex and TexWorks, the problem remains. The icon is still a non-curved arrow, pointing to the right. (Without MikTex, I am getting "PDFLatex is not properly configured". )

**Comment by stloeffler** [comment]
This should hopefully be solved in the latest development version, which you can download from https://nightly.link/TeXworks/texworks/workflows/cd/master/TeXworks-Windows and place anywhere on your computer (just don't overwrite your MiKTeX version just in case). As long as MiKTeX is installed, it should pick up pdflatex and related programs. If not, you can tell it where to find them via Preferences > Typesetting.

**Comment by vdlee37** [comment]
This has fixed the problem. Thank you very much!

**Comment by Eciftcibasi** [comment]
> This should hopefully be solved in the latest development version, which you can download from https://nightly.link/TeXworks/texworks/workflows/cd/master/TeXworks-Windows and place anywhere on your computer (just don't overwrite your MiKTeX version just in case). As long as MiKTeX is installed, it should pick up pdflatex and related programs. If not, you can tell it where to find them via Preferences > Typesetting.

I have same problem, but the link is not live anymore. can you help?
