### ISSUE TITLE
problem with macOS Monterey

### ISSUE THREAD

**Issue by matteo339** [TeXworks/texworks#975]
**Bug description:**
The preview window don't load .jpeg images

**General information:**
The problem occurs in several situations:
- Mac architecture: both chip Intel and chip Apple M2;
- TeXworks version: both 0.6.7 and 0.7;
- MacTeX version: both 2021 and 2022;
- LaTeX program: both pdfLaTeX and XeLaTeX and LuaLaTeX... and ConTeXt

**Comment by stloeffler** [comment]
Thanks for reporting. Could you provide some minimal example file(s) (preferably the .tex, .pdf, and .jpeg files separately) for further debugging?

**Comment by matteo339** [comment]
Here is an MWE (the example image is contained in the TeXLive distribution)
`% !TEX encoding = UTF-8 Unicode
% !TEX program = pdflatex

\documentclass{minimal}
\usepackage{graphicx}
 
\begin{document}
\includegraphics{example-image.jpg}
\end{document}`

Here is the compilation result (.pdf file)
<img width="500" alt="Screenshot pdf" src="https://user-images.githubusercontent.com/111273603/185073393-f9777a69-d9b6-4799-845e-5d477b44767d.png">

... and here is the image of "preview" window
<img width="500" alt="Screenshot texworks" src="https://user-images.githubusercontent.com/111273603/185071649-8b68c1a3-e3a4-4184-9cac-f19379cbd250.png">

**Comment by stloeffler** [comment]
Thanks for the MWE. It seems there was a problem with the compilation of the dependencies, which curiously seems to have gone unnoticed for quite some time. Hopefully the [latest development binaries](https://nightly.link/TeXworks/texworks/workflows/cd/master/TeXworks-macOS) work as expected now.

**Comment by matteo339** [comment]
I confirm that the [latest development binaries](https://nightly.link/TeXworks/texworks/workflows/cd/master/TeXworks-macOS) work correctly. Thank you
