### ISSUE TITLE
How should I change the default PDF viewer?

### ISSUE THREAD

**Issue by Srijandev** [TeXworks/texworks#980]
Hello, I apologise because this shouldn't be here :(

Is there a way I can change the default PDF viewer of TexWorks, If yes how?

Thank you in advance.

**Comment by stloeffler** [comment]
Indeed, for general questions the [mailing list](https://tug.org/mailman/listinfo/texworks) is a better place to ask.
If you mean to change how/where previews are shown, this currently cannot be customized as TeXworks always uses its (tightly integrated) internal previewer. There are a couple of (partial) workaround, though:
* In the internal previewer, you can go to "Scripts > Open in default viewer" to open the PDF in whichever application your operating system uses by default for displaying PDFs - this can usually be configured somewhere in your OS's file explorer or settings
* You can tell TeXworks not to open pdfs (which would use the internal previewer) after typesetting by going to Edit > Preferences > Typesetting, editing the typesetting tool(s) you use, and uncheck "View PDF after running". In that case, you'd have to open the PDF yourself.

In all cases, be aware that some (external) programs on some OSs (notably Acrobat on Windows) tend to "lock" PDFs they open, making it impossible for subsequent TeX runs to edit it until the PDF is closed again. IMO, this is a bug in the respective external programs, as locking PDFs is not at all necessary - but that's an entirely different discussion.
