### ISSUE TITLE
Reuse regex groups in replace text

### ISSUE THREAD

**Issue by Friedrich2** [TeXworks/texworks#985]
**Is your feature request related to a problem? Please describe.**
First, thanks for your great work! Second, I often have the problem to replace things under information preservation, i. e., the parts recognized by the regex should not be deleted by a "one single fits them all" replacement, but by a context-dependent insertion.

**Describe the solution you'd like**
Despite not being described in the manual, it is possible to use regex groups (even named regex groups!) in the search dialog. (c. f. screenshot)
Therefore, I would be happy being able to use regex groups in the replace dialog entry field too. One could use QString::replace to implement this. (see [here](https://doc.qt.io/qt-6/qstring.html#replace-11))

**Describe alternatives you've considered**
There are no alternatives which came to my mind -- up to keep using external tools like grep. (Not natively supported on Windows!)

**Caveat emptor**
This QString method is only available since Qt5, but 5 seems to be the lowest supported version, therefore no problem will arise.
![grafik](https://user-images.githubusercontent.com/34623166/208702601-04811169-af4b-45fa-a663-4ce94871266d.png)

**Comment by stloeffler** [comment]
The replace dialog does have a "regular expressions" option, and it can use capture groups for replacing. Unfortunately, Qt only supports numbered groups like `\1`, `\2`, ... in `QString::replace` (see [docs](https://doc.qt.io/qt-5/qstring.html#replace-11) and [source](https://code.qt.io/cgit/qt/qtbase.git/tree/src/corelib/text/qstring.cpp?h=5.15&id=ab28ff2207e8f33754c79793089dbf943d67736d#n4126)).

So in your case, you could turn "begin" into "ginbe" by using the replacement string `\2\1`.

There would theoretically be the possibility to try to substitute named references by their corresponding indices in the replacement text, but there would be many corner cases, issues with escape characters, etc.

**Comment by Friedrich2** [comment]
Very interesting, thanks! In an ideal world, I would be happy if it could be mentioned explicitly in the TeXWorks manual, but since I suppose that neither you nor I have the time to do it, it is o. k. to close this issue.
