### ISSUE TITLE
Pixelated preview window

### ISSUE THREAD

**Issue by pdedecker** [TeXworks/texworks#989]
I am a long-time fan of the program! But the preview window looks very pixelated with Flathub-installed Texworks on a fresh install of Kubuntu 22.10. The rest of the program and the source editor look crisp. The attached screenshot shows a sample tex file in action.

Perhaps relevant: the Display Configuration in the KDE settings is set to a global scale of 125%.
![Screenshot_20230122_175114](https://user-images.githubusercontent.com/1118089/213928360-c410f37d-cd01-4d26-b6ed-9942fa4a9480.png)

**Comment by pdedecker** [comment]
This seems to have been fixed in 0.6.8 installed from Flathub. Thanks!

**Comment by stloeffler** [comment]
Great to hear, thanks for testing.
