### ISSUE TITLE
High memory usage in TeXworks in MacOS

### ISSUE THREAD

**Issue by fact0real** [TeXworks/texworks#990]
As a daily user of TeXworks software, I noticed that the amount of RAM usage is high and unusual. For a normal file of about 1000 lines, 2 GB of RAM is not logical at all. Another noteworthy point is the increase of this value over time, starting from 350 MB and increasing every moment. The OS is Ventura 13.2 and the CPU is Apple M1 Pro.

**Comment by stloeffler** [comment]
Thanks for reporting. This sounds like a duplicate of #973 - can you confirm that.

Also:
* What version of TeXworks are you using (and where did you download it from)?
* Is the RAM usage increasing even when not doing anything, or only during "normal operation", in particular zooming and/or scrolling in the PDF?

**Comment by fact0real** [comment]
Yes, it duplicated [#973](https://github.com/TeXworks/texworks/issues/973).
