### ISSUE TITLE
Release Plan for 0.6.8?

### ISSUE THREAD

**Issue by hpreusse** [TeXworks/texworks#991]
Just a short question. You did not put a date on the 0.6.8 milestone: is there already a time frame for release?

Background: the Debian project plans to do a release this year and there is only a limited amount of time left. I don't want to put pressure on you, I just want to know if the next release is around the corner or if it takes a longer time. Many thanks!

**Comment by stloeffler** [comment]
We have now entered feature freeze and I hope to release 0.6.8 by the end of February/beginning of March, if no major problems pop up. Does this fit into your deadlines?

**Comment by hpreusse** [comment]
> We have now entered feature freeze and I hope to release 0.6.8 by the end of February/beginning of March, if no major problems pop up. Does this fit into your deadlines?

Current time frame is:

- 2023-02-12 - Milestone 2 - Soft Freeze: no new packages, delayed migration
- 2023-03-12 - Milestone 3 - Hard Freeze - key packages and packages without autopkgtests need a manual unblock for migration
- TBA - Milestone 4 - Full Freeze all packages need a manual unblock for migration

We have a working test suite, hence we can upload even after mid of march. As there are no packages depending on texworks and it is not needed by other packages for building a fresh upload does not have impact to other packages.

So, yes it does fit in our deadlines. Many thanks!

**Comment by stloeffler** [comment]
Perfect, thanks.

**Comment by stloeffler** [comment]
For reference, 0.6.8 is out now.
