### ISSUE TITLE
Unicode management of the terminal output

### ISSUE THREAD

**Issue by jlaurens** [TeXworks/texworks#994]
**Bug description:**

I sometimes log to the terminal the sequence of unicode characters
▶︎▶︎▶︎▶︎▶︎▶︎▶︎▶︎▶︎▶︎ 
TeXworks sometimes displays it in the log window with extra spurious characters that do not exist in the log file, for example
▶︎▶︎▶︎▶︎▶���▶︎▶︎▶︎▶︎▶︎ 
Maybe some buffering problems?

**Steps to reproduce the problem:**

Very difficult to get a MWE.

**Expected behavior:**

**General information:**
_TeXworks version_: 0.6.8
_TeXworks obtained from_: texlive
_Operating system_: Ventura 13.2.1

**Additional information:**

**Comment by stloeffler** [comment]
Thanks a lot for reporting. I managed to reproduce this issue, and it seems to be caused by lualatex sometimes flushing the output in the middle of a multi-byte utf-8 code. This should now be handled correctly.
